### ISSUE TITLE
Loading image from url requires a image file extension

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1039]
# Context
This url : https://via.placeholder.com/150 link to a correct image. But I cannot open it with DocArray

```python
from docarray.documents import Image

img = Image(url='https://via.placeholder.com/150')
img.url.load()
>>>
E   pydantic.error_wrappers.ValidationError: 2 validation errors for Image
E   tensor
E     field required (type=value_error.missing)
E   url
E     Image URL must have one of the following extensions:('png', 'jpeg', 'jpg') (type=value_error)

pydantic/main.py:342: ValidationError

```

Is it expected or is it a bug ?

**Comment by samsja** [comment]
@anna-charlotte what do u think ?

**Comment by samsja** [comment]
then lets try to come up with a PR that remove this limitation

**Comment by JohannesMessner** [comment]
> maybe we only do this validation for not remote urls

Couldn't I also save a an image locally without a file extension?
I think there is a general conflict between validation and a "let's just give it a try" approach, so maybe for use cases like this users should just turn off validation

**Comment by samsja** [comment]
> Couldn't I also save a an image locally without a file extension?

yeah technically you are right

**Comment by RStar2022** [comment]
Hey @samsja could you please assign me this issue? 
Isn't it just adding option to the issue is the solution?
