### ISSUE TITLE
v2: filter query languague

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1040]
# Context

We need to implement the filter query language equivalent to docarray v1 : https://docarray.jina.ai/fundamentals/documentarray/find/#query-by-conditions

One of the goal is to keep compatibility with jina filetering in topology https://docs.jina.ai/concepts/flow/add-conditioning/

Under the hood the framework which handle the operation should rely on python operator. If we want to support a new type in the filtering language we should overload the operator of the type so that it works with the input in the query language. 

At first filtering will only work on string and numeric field. We don't close the door to filtering on tensor but it is not plan for v2 initial release. One of the limitation is that the query should be json compatible so it cannot call torch or numpy object in it

**Comment by JoanFM** [comment]
Closed by #1051
