### ISSUE TITLE
weaviate fails to save the chunk embedding

### ISSUE THREAD

**Issue by tugot17** [docarray/docarray#1061]
**Describe the bug**

I have a `DocumentArray` storing documents with chunks. For persistant storage I use `weaviate `. After I add the embedding to each chunk the embedding is not stored and is nowhere to be found, The problem doesn't occur if I don't use the weaviate storage. 

**To Reproduce**
```py
from docarray import DocumentArray, Document, dataclass
doc_one = Document(text="one")
doc_two = Document(text="two")

doc_one.chunks = [Document(text=c) for c in doc_one.text]
doc_two.chunks = [Document(text=c) for c in doc_two.text]

da = DocumentArray(
    storage="weaviate",
    config={"name": "Test", "host": "localhost", "port": 8080},
)

with da:
    del da[:]

da.extend([doc_one, doc_two])
with da:
    for doc in da:
        for chunk in doc.chunks:
            chunk.embedding = [1, 2, 3]

for doc in da:
    for chunk in doc.chunks:
        print(chunk.embedding)
```

And the produced output is the following: 

```
None
None
None
None
None
None
```

**Expected behavior**
If the `da` is replaced with `da = DocumentArray()` the output is correct. `da.sync()` also doesn't fix the issue. 

```
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Docarray 0.21.0, weaviate:1.16.1

**Comment by JoanFM** [comment]
the thing here is that  when you do:

```
for doc in da:
   # here Doc exsits in memory, is not changed automatically in the DocumentStore:
   # you should do `da[doc.id] = doc` and this should actually update it

**Comment by JoanFM** [comment]
We are redesigning our DocStores implementaion to clarify these not so intuitive behaviors
