### ISSUE TITLE
Allow stacked DocumentArrays to be constructed from list of Documents

### ISSUE THREAD

**Issue by Jackmin801** [docarray/docarray#1068]
**Is your feature request related to a problem? Please describe.**
The pytorch dataloader's pin_memory implementation requires the data to have this signature
```python
type(data)([pin_memory(sample, device) for sample in data])
```

This signature does not exist for Stacked DAs, and thus, they cannot be used as the return type of a dataset.

**Describe the solution you'd like**
An implementation of this constructor for Stacked DAs

**Describe alternatives you've considered**
None

**Additional context**
This might not resolve the issues with pin_memory but it would be a step in the right direction.

**Comment by Jackmin801** [comment]
Deferred as the lack of `pin_memory` support was identified to not be a significant slowdown at the moment

**Comment by JoanFM** [comment]
This will be handled by #1079

**Comment by JoanFM** [comment]
I would like to be sure that the PR fixing this actually tackles the underlying problem

**Comment by Jackmin801** [comment]
Yes it does. Patching the `init` and `from_document_array` in this hacky way allows the `pin_memory` to work.
So it is about having a constructor that can take list value.

```python
    def __init__(
        self: T,
        docs: DocumentArray,
    ):
        if len(docs) > 0:
            docs = DocumentArray[type(docs[0])](docs)
        self._doc_columns: Dict[str, 'DocumentArrayStacked'] = {}
        self._tensor_columns: Dict[str, AbstractTensor] = {}

        self.from_document_array(docs)

    def from_document_array(self: T, docs: DocumentArray):
        self._docs = DocumentArray(docs)
        #self.tensor_type = self._docs.tensor_type
        self.tensor_type = TorchTensor
        self._doc_columns, self._tensor_columns = self._create_columns(
            docs, tensor_type=self.tensor_type
        )

```

**Comment by Jackmin801** [comment]
The reason we didnt do a simple patch to it was because we could not reach consensus on whether we liked double parametrization. This is necessary because of this line.

```python
        #self.tensor_type = self._docs.tensor_type
        self.tensor_type = TorchTensor
```

`tensor_type` needs to be class level information. However it is currently instance level information.
If we promote it to class level, the type needs to know about it. So we would have double parametrization e.g.
`DocumentArray[PairTextImage, TorchTensor]`
