### ISSUE TITLE
`DocumentArray` and `DocumentArrayStacked` should be `typing.Generic`

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1077]
since DocumentArray(Stacked) is generic in the type of Document it takes (`DocumentArray[MyDoc]`), it should inherit from `typing.Generic`.
This would also let us express that for any typed DocumentArray, operations return instances of `MyDoc`, not just any `BaseDocument`.

This is also the reason why currently we have to all `__class_getitem__` manaually in a lot of places

**Comment by JoanFM** [comment]
Can u paste an example of how u would update some `type hints` with this?

**Comment by JohannesMessner** [comment]
I think the main thing is that both document array variants should inherit from `typing.Generic` and afterwards we should be able to remove a lot of hackery.
For example, you will se a lot of `da/self/cls.__class_getitem__(...)` or in the codebase, because mypy is not happy with `da[...]`. The same would be true for anyone using DocArray and checking their code with mypy. Inheriting from `typing.Generic` should fix it.

I'm not sure if any other type hints would change based on this, though.

**Comment by samsja** [comment]
@JohannesMessner we already have the generic things. I think this is a bug in mypy

**Comment by JohannesMessner** [comment]
Ok then let's close?
