### ISSUE TITLE
Acess the values of Multimodal data

### ISSUE THREAD

**Issue by tugot17** [docarray/docarray#1080]
**Is your feature request related to a problem? Please describe.**
I want to store the custom, multimodal documents in the `DocumentArray`, but it is impossible to access their values once they are in the `DocumentArray`. The documentation example in [acess the data](https://docarray.jina.ai/datatypes/multimodal/#access-the-data) doesn't work after the documentation is put into `DocumentArray`

**Code**
```py
from docarray import DocumentArray, Document, dataclass
from docarray.dataclasses.enums import DocumentMetadata
from docarray.typing import Text, JSON


@dataclass
class DataDocument:
    doc_title: Text
    doc_metadata: JSON


doc = DataDocument(doc_title ="Tile document", doc_metadata={"field1": "value1"})
doc = Document(doc, chunks=[Document(text="text1"), Document(text="text2")])

da = DocumentArray()
da.append(doc)

print(da[0].doc_title.text)
print(da[0].doc_metadata.text)

>> text1
>> text2
```
For some reason, I get the value of text in chunks and not the values from the original document. 

**The expected behavior would be:**
```
>> Tile document
>> ERROR: There is no text field in the JSON object.
```
Moreover; in the `_metadata` field of a document, I was able find the types of the fields from the original `DataDocument` but not its values

**Comment by JoanFM** [comment]
Hello @tugot17 ,

We are working on refactoring DocArray to a more shchema-free data structure https://github.com/docarray/docarray/tree/feat-rewrite-v2#readme that I believe you will enjoy as a user of `dataclass`.

We do not plan to iterate further on this direction for the current DocArray direction, so I would suggest to migrate to this new v2 feature and follow its progress in https://github.com/docarray/docarray/issues/780.

This way you can influence the direction and check if the new direction would meet your needs.

**Comment by tugot17** [comment]
@JoanFM thanks for the quick reply. Is there as expected date of an official release of v2?

**Comment by JoanFM** [comment]
Hey @tugot17 ,

The release 0.30 is ready and you can already use with all the improvements.

**Comment by tugot17** [comment]
congrats for great work and making it in April 📅, great work 😄
