### ISSUE TITLE
docarray full install command

### ISSUE THREAD

**Issue by Keertiraj** [docarray/docarray#1087]
**Is your feature request related to a problem? Please describe.**

I installed the basic docarray as described in the [document](https://docs.docarray.org/get-started/install/). I face with dependency errors, while running the examples that had dependency on scipy package. 

**Describe the solution you'd like**

The `pip install "docarray[full]"` command would have resolved it. However, the full command is in the 3rd tab and new users could forget to look into this tab. Because of this (basic deployment), when the user face the errors when executing python examples in the documentation, the user could potentially stop using the docarray library.

My proposal is to "**Full install**"  command in the first tab, so that the user installs all the libraries by default.

**Comment by alexcg1** [comment]
I think this is being addressed by #1086
