### ISSUE TITLE
incorrect version in the clipboard - pip install docarray

### ISSUE THREAD

**Issue by Keertiraj** [docarray/docarray#1088]
**Describe the bug**

When i install the basic docarray, using the docarray [documentation](https://docs.docarray.org/get-started/install/), i see the  different version deployed in my local machine. 

What i see in my location machine (version: 0.21):

![image](https://user-images.githubusercontent.com/4416580/217018303-1250a27b-8b2d-42e3-9e4f-c739cc3e2077.png)

The docarray version in the documentation:

![image](https://user-images.githubusercontent.com/4416580/217017753-2a5e7bac-843b-40a8-8688-9728a2799dcb.png)

**Expected behavior**

The new version of the docarray needs to be updated in the [documentation](https://docs.docarray.org/get-started/install/)

**Comment by JoanFM** [comment]
We are not going to make sure this is updated in every version. We may be able to just add a message stating that the version willl match the one u have. @alexcg1 please check if is worth the effort or we close it

**Comment by alexcg1** [comment]
@JoanFM what do other projects do? Normally I'd check version via `pip freeze | grep docarray`. I've seldom if ever checked `__version__` so I don't personally think its worth the effort
