### ISSUE TITLE
Support primary field definition to have a less verbose API

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1096]
# Context

this is a follow-up issue to : https://github.com/docarray/docarray/issues/1056

We fix the issue of a API which is a big to verbose in this PR : https://github.com/docarray/docarray/pull/1067
and this PR : https://github.com/docarray/docarray/pull/1067

Nevertheless, this only applies to our predefined documents. It is not handled in a generic manner for every Document.

Let's take an example:

```python

from docarray import BaseDocument


class MyDoc(BaseDocument):
   a: str
   b: Optional[str]
   c: Optional[str]

doc = MyDoc(a='hello')

```

it would be better if we could do

```python

doc = NyDoc('hello')

```

 the question is how to chose ? 

a solution might be to have a `default_field` in Document

```python

class MyDoc(BaseDocument):
   a: str
   b: Optional[str]
   c: Optional[str] 
   
   class Config:
       primary_field = 'a'

doc = NyDoc('hello')
doc.a == 'hello'

```

this should apply as well for validation

**Comment by JoanFM** [comment]
This `primary_field, coulnd't it be a `Field()` ?

**Comment by JohannesMessner** [comment]
would the `Field()` approach persist through inheritance?
