### ISSUE TITLE
use pydantic generic model for the tensor type

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1105]
# Context

currently, the predefined documents have use the `AnyTensor` type which is just a Union of `TorchTensor`, `NdArray` and `TfTensor`.

This create a problem a the DocumentArrayStack level where we need to know which type it will be. We cannot stack with a mix of torch tensor and numpy tensor. 

We initially introduced the `tensor_type` argument in `DocumentArray` and `DocumentArrayStacked` see this pr : https://github.com/docarray/docarray/pull/966

Nevertheless we face several limitations because of this new behavior (example : https://github.com/docarray/docarray/issues/1085)

Moreover the usage is not straightforward and not clear.

We believe we should rely on the typing system to express this rather than on this keyword arguments.

The main idea is to use [GenericModel](https://docs.pydantic.dev/usage/models/#generic-models) from Pydantic inside our predefined documents.

Instead of doing

```python

from docarray import BaseDocument
from docarray.typing import AnyTensor, TorchTensor, NdArray

class MyDoc(BaseDocument):
    tensor : AnyTensor

from docarray import DocumentArray

da_torch = DocumentArray[MyDoc]([], tensor_type=TorchTensor)
da_numpy = DocumentArray[MyDoc]([], tensor_type=NdArray)
```

we should do 

```python
from typing import Generic, TypeVar
from pydantic.generics import GenericModel

from docarray import BaseDocument
from docarray.typing import AbstractTensor, TorchTensor, NdArray


TensorT = TypeVar('TensorT', bound=AbstractTensor)

class MyDoc(BaseDocument, GenericModel, Generic[TensorT]):
    tensor : TensorT

from docarray import DocumentArray

da_torch = DocumentArray[MyDoc[TorchTEnsor]]([])
da_numpy = DocumentArray[MyDoc[NdArray]]([])
```

ideally we should be able to do `da_numpy = DocumentArray[MyDoc]([])` which should be equivalent to  `da_numpy = DocumentArray([])`

**Comment by Jackmin801** [comment]
This might not be possible. The reason is that the `tensor_type` TypeVar has to cascade to the Document's fields.

For example, in the ImageDoc:
```python
from pydantic.generics import GenericModel
from typing import Generic, TypeVar, Optional
from docarray.typing.tensor.image import ImageTensor
from docarray.typing.tensor.embedding import AnyEmbedding

TensorType = TypeVar('TensorType')
class ImageDoc(BaseDocument, GenericModel, Generic[TensorType]):
    image: Optional[ImageTensor[TensorType]]
    embedding: Optional[AnyEmbedding[TensorType]]
```

But the cascading will fail because the type definitions of the fields are not generic.

One way to try and 'cheat' a generic would be to create a mapping class. Override `__class_getitem__` with and return the class we want.
But if you try to implement this mapping class, there is an edge case. What should you return when the TypeVar is passed to `__class_getitem__`. This happens when the above document is defined. What can you return that informs the generic resolution code that it needs to resolve this later?

```python
from docarray.typing.tensor.image.image_ndarray import ImageNdArray
from docarray.typing.tensor.image.image_torch_tensor import ImageTorchTensor
from docarray.typing import TorchTensor, NdArray

TensorType = TypeVar('TensorType')

IMAGE_TENSORS = {
    TorchTensor: ImageTorchTensor,
    NdArray: ImageNdArray,
}

class ImageTensor(Generic[TensorType]):
    def __class_getitem__(cls, item):
        if not isinstance(item, TypeVar):
            return IMAGE_TENSORS[item]
        else:
            # What do you return here?
            return cls
```
