### ISSUE TITLE
docarray code execution through Jupyter Notebook

### ISSUE THREAD

**Issue by Keertiraj** [docarray/docarray#1110]
**Is your feature request related to a problem? Please describe.**

At the moment, to run the python code in the [docarray](https://docs.docarray.org/) tutorial, the user has to copy the code snippet  and execute the code in the local machine. This process is time consuming and error prone. 

**Describe the solution you'd like**

1. Write a Jupyter Notebook for the code examples, so that they are directly runnable.

**Comment by samsja** [comment]
@Keertiraj we will make this a priority in the documentation for DocArray v2

**Comment by samsja** [comment]
Btw having the possibility to run our documentation in notebook will allow us to actually test that all of our documentation snippets can be run by running the notebook in our CI.

Issue like https://github.com/docarray/docarray/issues/1108
and https://github.com/docarray/docarray/issues/1109 would have been catch earlier for instance

**Comment by alexcg1** [comment]
> I agree with this comment. IMO we should have a google colab button on each documentation page that will open the same page in a colab where users can interact directly.
> 
> @alexcg1 FYI

I like it. Just bear in mind that someone has to be responsible for maintaining it. We used to have a lot of Colab notebooks, but it's easy to lose track of them and let them get code rot
