### ISSUE TITLE
Video Tutorial for Docarray

### ISSUE THREAD

**Issue by Keertiraj** [docarray/docarray#1112]
**Is your feature request related to a problem? Please describe.**

Currently, the user has to go through the documentation and execute the code snippet to understand the docarray.

**Describe the solution you'd like**

Some users could prefer to watch the video to understand the product quickly.  The guided videos will help increase the adoption rate of the solution.

**Comment by samsja** [comment]
With DocArray v2 coming I believe it is too early to prepare a video as the user experience will significantly change.

But I agree that video is an important medium for communication and user onboarding.

Nevertheless we need to keep in mind that until docarray is stable (maybe a couple of month after v2 release) API will slightly change and therefore we need to carefully decide when to do such a video to avoid it being obsolete after a couple of weeks
