### ISSUE TITLE
DocumentArray proto optimization

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1116]
# Context

At the moment we save in the `DocumentProto` under the `docarray_type` string the exact type of each field (this string is coming from the `_registed_proto` decorator). This a way to "save" the schema of our Document to load at after deserialization. Keep in mind that this add extra data in the Document proto payload. 

In a DocumentArray all of the document are homogene (i,e follow the same schema). Therefore it is unscary to save  this schema information more than once.

We should optimize the proto sterilization of DocumentArray by only saving this data once

**Comment by JohannesMessner** [comment]
> In a DocumentArray all of the document are homogene (i,e follow the same schema)

This is true _most_ of the time, but not always, right? ``DocumentArray([....])` is valid, no?

**Comment by samsja** [comment]
> This is true most of the time, but not always, right? DocumentArray([....]) is valid, no?

Yes and in this case, I guess we cannot optimize.

Though tbf I think we should remove `DocumentArray([...])` but this is another discussion.

**Comment by samsja** [comment]
> This is true most of the time, but not always, right? DocumentArray([....]) is valid, no?

Yes and in this case, I guess we cannot optimize.

Though tbf I think we should remove `DocumentArray([...])` but this is another discussion.

**Comment by samsja** [comment]
we close this for now as we want to keep the proto of DocumentArray simple.

It being a repeat of the Document is a neat feature. It allows you to easily reason outside of DocArray Python.

Moreover with grpc and protobuf compression this redundancy will not be a big problem.

@JoanFM feel free to add other argument to keep it like this
