### ISSUE TITLE
automatic translation of document schema

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1119]
# Context

we need to be able to translate a document to a different schema.

example:

```python
    class A(BaseDocument):
        url: AnyUrl
        tensor: NdArray

    class B(BaseDocument):
        link: AnyUrl
        array: NdArray
```

How to do it is still not decided

**Comment by agaraman0** [comment]
Hey @samsja  would like to pick up this one, if not fixed :grimacing:

**Comment by samsja** [comment]
This ticket is not ready to be picked we are not decided if we even need this features anymore.

@agaraman0 what about this one ? https://github.com/docarray/docarray/issues/980

**Comment by JoanFM** [comment]
This we will not take for now, if we aim to solve this we will open a new more detailed issue
