### ISSUE TITLE
Put all docarray method in document and da into a common namespace

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1135]
# context

as we allow flexible schema we need a way to prevent user to use a key name that is already used by docarray. The best way to do it is to have a namespace for al of the method of `Document`. 

Example:

`doc.from_protobuf -> doc.doc_from_protobuf`

or 

`doc.da_from_protobuf`

then we just need to tell the user you cannot have a key name that start with `doc` as it is reserved for docarray method.

Pydantic v2 will have a similar approach : https://docs.pydantic.dev/blog/pydantic-v2/#model-namespace-cleanup

**Comment by AsRaNi1** [comment]
HI! 
I would please like to work on this issue.

**Comment by samsja** [comment]
Hey @AsRaNi1 your contribution would be gladly appreciate!

The idea is that for every not private function on the class BaseDocument and the class `AnyDocumentArray`, `DocumentArray` and `DocumentArrayStacked` we want to rename to add the `doc` namespace.

Feel free to ask question if this is not clear.


FYI: this issue concern DocArray v2, you can see here how to contribute to v2 : https://github.com/docarray/docarray/blob/feat-rewrite-v2/CONTRIBUTING.md

You will need to create a PR towards this dev branch of DocArray v2 : https://github.com/docarray/docarray/tree/feat-rewrite-v2

**Comment by AsRaNi1** [comment]
> Hey @AsRaNi1 your contribution would be gladly appreciate!
> 
> The idea is that for every not private function on the class BaseDocument and the class `AnyDocumentArray`, `DocumentArray` and `DocumentArrayStacked` we want to rename to add the `doc` namespace.
> 
> Feel free to ask question if this is not clear.
> 
> FYI: this issue concern DocArray v2, you can see here how to contribute to v2 : https://github.com/docarray/docarray/blob/feat-rewrite-v2/CONTRIBUTING.md
> 
> You will need to create a PR towards this dev branch of DocArray v2 : https://github.com/docarray/docarray/tree/feat-rewrite-v2

Yes sure!!
I'll form a PR soon

**Comment by AsRaNi1** [comment]
@samsja changes in the names of the not private methods of the following classes are made, the test files and some other files have the previous name without the `doc` namespace so am changing that currently and then will form the PR.
example of the changes made:  `stack`  --> `doc_stack`

**Comment by samsja** [comment]
Nice, in which PR did you do your modification ?

**Comment by AsRaNi1** [comment]
> Nice, in which PR did you do your modification ?

I have not made a PR yet, 4 tests are failing and i'm figuring out why! 
Mostly because the name of the methods has changed so i am looking for all instances where the objects for these classes have been created and methods are called, i may have missed some instances

**Comment by AsRaNi1** [comment]
@samsja I have changed all the references for the methods in the codebase, but it is throwing multiple errors while testing. 
Shall i change the names of methods in other classes aswell?

**Comment by samsja** [comment]
> Shall i change the names of methods in other classes aswell?

only on `BaseDocument` and on `DocumentArray` I believe

**Comment by RStar2022** [comment]
Hi @samsja I would like to take the issue.

**Comment by samsja** [comment]
@RStar2022 Lets wait we did not figure it out on far we want to go with this issue

**Comment by JoanFM** [comment]
Action point:

- [ ] Do not implement it.
- [ ] Check if we can warn user when instantiating class.

**Comment by jupyterjazz** [comment]
There's already an informative error message thrown when using an invalid field name, so we can close the ticket.


```python
from docarray import BaseDocument

class MyDoc(BaseDocument):
    to_bytes: str

doc = MyDoc(to_bytes='strrr')
```

```
NameError: Field name "to_bytes" shadows a BaseModel attribute; use a different field name with "alias='to_bytes'".
```
