### ISSUE TITLE
Try out turning off pydantic validation

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1142]
I see two sub-issues around this:
1. I think certain users that either just want to script some stuff python-style, or want to shave off some milliseconds here and there, might want to turn off data validation globally. We don't offer this currently, but I think we should
2. Even if we don't offer this, people can still manually turn off validation in the pydantic configs. But we rely on validation in certain places to do data parsing / casting. We need to investigate if/how/where things break when validation is turned off

**Comment by samsja** [comment]
Turning off validation ( see below) makes only 2 tests fail. But this test actually expects the validation to happen so it is normal that it is failing. This means we can use DocArray while turning off validation.
```python
class BaseDocument(BaseModel, IOMixin, UpdateMixin, BaseNode):
    """
    The base class for Documents
    """

    id: Optional[ID] = Field(default_factory=lambda: ID(os.urandom(16).hex()))

    class Config:
        json_loads = orjson.loads
        json_dumps = orjson_dumps_and_decode
        json_encoders = {dict: orjson_dumps}

        # validate_assignment = True
        validation = False
```
