### ISSUE TITLE
DocArray v2 third alpha release note

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1153]
# DocArray v2 alpha release

DocArray v2 has its third alpha release as planned in the [roadmap](https://github.com/docarray/docarray/issues/780)

# What is new ?

### Tensorflow support (#1064) (#1098)
In this version we added TensorFlow support to v2.
Most importantly, this includes a `TensorFlowTensor` class and a corresponding `TensorFlowCompBackend`.

```python
import tensorflow as tf

from docarray import BaseDocument, DocumentArray
from docarray.typing import TensorFlowTensor


class MyDoc(BaseDocument):
    title: str
    tensor: TensorFlowTensor


da = DocumentArray[MyDoc](
    MyDoc(title=f'hello {i}', tensor=tf.zeros((224, 224, 3))) for i in range(100)
)
```

### Pretty printing with rich (#1043)
Add pretty print and `.summary()` for Document's as well as DocumentArray's:
For a **Document**: 
<img width="634" alt="image" src="https://user-images.githubusercontent.com/73693835/220151984-865f79b8-d72e-4fd5-bad4-392bd3ddfa42.png">

For a **DocumentArray**:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/73693835/220152131-4f24554c-20e7-42be-af6b-238b26914bc8.png">

### Display of different multi modal data type (#1113) (#1136)
You can now display your multi modal data with our predefined documents and types from a notebook! This applies to audio, image, video, as well as 3D data.
You can simply call `.display()` on the Documents url or its tensor(s):

For `PointCloud3D`:
```python
doc = PointCloud3D(url='tests/toydata/tetrahedron.obj')
doc.tensors = doc.url.load(samples=10000)
doc.tensors.display()
# or via url
doc.url.display()
```

<img width="217" alt="image" src="https://user-images.githubusercontent.com/73693835/217781368-f089c0e4-4e77-41b1-9574-9ef510f2b3ca.png">

For `Mesh3D`:
```python
doc = Mesh3D(url='tests/toydata/tetrahedron.obj')
doc.tensors = doc.url.load()
doc.tensors.display()
# or via url
doc.url.display()
```

<img width="300" alt="image" src="https://user-images.githubusercontent.com/73693835/217790889-cedacb31-e414-4892-9644-704218d514dc.png">

### Pytorch Multi Modal dataset
You can now easily utilise DocumentArrays in PyTorch training scripts using `MultiModalDataset`. 
All you need is a DocumentArray and a dictionary of preprocessing functions and you’re up and running.
```python
from torch.utils.data import DataLoader
from docarray import DocumentArray, BaseDocument
from docarray.data import MultiModalDataset
from docarray.documents import Text

class Thesis(BaseDocument):
    title: Text

class Student(BaseDocument):
    thesis: Thesis

da: DocumentArray[Student] = get_students()
ds: MultiModalDataset[Student] = MultiModalDataset[Student](da, preprocessing={"thesis.title": embed_title, "thesis": normalize_embedding})
loader: DataLoader = DataLoader(ds, batch_size=4, collate_fn=MultiModalDataset[Student].collate_fn)

# Use your loader just like any other dataloader for awesome DL training
```

### More serialization options

**Comment by alexcg1** [comment]
Is this still a WIP? I see a title at the bottom with nothing below it

**Comment by samsja** [comment]
yes still wip

**Comment by alexcg1** [comment]
OK, ping me when ready for me to review

**Comment by samsja** [comment]
As discuss before we won't need this release anymore
