### ISSUE TITLE
Support for Union types, to map XML to Document

### ISSUE THREAD

**Issue by scott-martens** [docarray/docarray#1157]
I would like to be able to convert between XML (and similar structured documents) and Document, so that I can take existing documents and apply neural methods to them, i.e. search for matches in the document's parts and match the result to the source document structure.

Document already supports chunks of different types, so I could map XML to a nested Document structure, but I would have to use the tags to create an address map from the original XML to the Document. For example, give each Document chuck a tag "xpath" with values like "/article/section[1]/subsection[3]".

But since there is now support for mapping pydantic dataclasses directly to Document, I tried doing it that way. I constructed a simple XML document and a matching schema as a dataclass:

```@dataclass
class Section:
    title: Text
    main: List[Union[Text,Image]]
```

This matches the schema of a mixed content section in XML. But it doesn't work:

`TypeError: Unsupported type annotation inside Iterable: typing.Union[~Text, ~Image]`

In general, I'd like to see features that make it easier to map from structured document types via pydantic to Document and DocArray, so I can use them in an out-of-the-box way to handle structured data. To do that, it needs to support XML types that correspond to Union and Optional, and maybe should include some functionality for mapping data from XML attributes to the 'tag' field in Document. Also, the ability to map back from Document to a structured source would be nice, but I can't think of a fully generic way of doing that.

**Comment by JoanFM** [comment]
Due to the lack of activity and waiting to see if the issur is raised again after 0.30 release, I will close this issue
