### ISSUE TITLE
Check that we are doing proper file extension validation for all data types

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1166]
[Here](https://github.com/docarray/docarray/pull/1155) we make sure to do proper file extension validation for audio files paths, meaning:

- we have an exhaustive list of all audio file extensions
- if a different extension is given to the auio url, fail validation
- no _no_ extension is given, pass

We need to apply the same logic to all other modalities as well, such as image, text, video, ...

**Comment by hrik2001** [comment]
Hi! I am eager to work on this issue and have also given a heads up at the docarray discord :)

I will be making separate PRs for each modality and will be linking them to this issue.

**Comment by JohannesMessner** [comment]
After some consideration, we have changed our mind on this ticket. We no longer think it is a good idea to do this. You can see the reasons for this, and the follow-up work that needs to be done, here: https://github.com/docarray/docarray/issues/1309
