### ISSUE TITLE
unify some naming

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1172]
sometimes we call our schmas/paremetrization `self._schema`, sometimes it is `self.document_type`, other times it is `self.doc_schema`. This should be unified.

**Comment by samsja** [comment]
@agaraman0 we want to rename all of them to `self.document_type`

**Comment by agaraman0** [comment]
Hey @samsja  i am not able to find `self._schema` and `self.doc_schema` in codebase, can you point out some files lines just to get context

**Comment by samsja** [comment]
@JohannesMessner may you give a bit more context here ?

**Comment by JohannesMessner** [comment]
Turns out, I was the only fool to not use `document_type`, I use `_schema` in the document indices.
But actually i would not want to change that to `document_type`, I think that would be confusing in that context.

So either rename everything to `_schema`, or just close the issue?

**Comment by samsja** [comment]
I think we can just close the issue
