### ISSUE TITLE
Support ES 7.10.2 and latest together

### ISSUE THREAD

**Issue by wqh17101** [docarray/docarray#1181]
ES changed their Apache license  to SSPL which is a business-unfriendly license after 7.10.2.
For the companies , they prefer the business-friendly license. So they prefer 7.10.2.
For docarray, i see that https://github.com/docarray/docarray/blob/5de8fd4519020e3cf6ec16911982059548f69b08/setup.py#L82
Docarray only supports `es>=8` which is incompatible with `es server 7.10.2`. This will make docarray unavailable for company.

**Comment by JoanFM** [comment]
We will take into account for next v2 release

**Comment by samsja** [comment]
Yes agree with @girishc13 there are no license problem with the ES python client

**Comment by girishc13** [comment]
We can support compatibility as mentioned [here](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/migration.html#migration-compat-mode).

**Comment by wqh17101** [comment]
@samsja @girishc13  
I do not mean that.
I do not mean that the client has the license problem.
You know that client should match the server. 
To prevent the license problem, company will use the server v7.10.2. So they use elasticsearch-py v7.10.2 to match.
Follow https://github.com/elastic/elasticsearch-py/issues/2150

**Comment by samsja** [comment]
Ah okay now it makes sense what you are asking for. Sorry for the misunderstanding haha.

So your point is that we should support ES7 and above right ?

**Comment by wqh17101** [comment]
@samsja You got it!
