### ISSUE TITLE
Advanced Tensor typing features

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1185]
# Context

We currently support notation like this

```python
class MyDoc(BaseDocument):
    arr: NdArray
    image_arr: NdArray[3, 224, 224]
    square_crop: NdArray[3, 'x', 'x']
```

which will validate the shape of  `image_ar` and `square_crop`.

## More advanced feature

I can think of several use cases that we don't cover yet.

### 1 - generic behavior

In some case I just want to check that the first dim of the tensor has an exact value. 
Example:
```python
    def f(batch: NdArray[100, ... ])
```

Here I want a batch of size 100, the rest I don't care it could be a (100, 3, 224, 224) or (100, 512).

### 2 - TypeVar like

At the moment we can reuse the same "letter" inside one shape :  `NdArray[3, 'x', 'x']` this means that we expect a tensor with the two last dim to be the same value.

But we cannot do this across two variables.

```python
def f(a: NdArray['x', 512], b: NdArray['x', 512]) -> NdArray['x', 10]: 
   ...
```

we might need to introduce a TypeVar like feature to do such a thing.

This will only work for type hint though as we don't have cross object validation (unless we use pydantic root validator)

**Comment by jupyterjazz** [comment]
first feature is implemented, decided to skip the second one
