### ISSUE TITLE
Initialization and construction of a `Document` and `DocumentArray` takes too long

### ISSUE THREAD

**Issue by anna-charlotte** [docarray/docarray#1189]
**Describe the bug**
Initialization and construction of a `Document` and `DocumentArray` takes a lot of time compared to simple list initialization:

```python
from time import time 
n_docs = 1_000_000

# list initialisation
start_time = time()
numbers = [i for i in range(n_docs)]
duration = time() - start_time
print(f"duration list init = {duration}")

# DocumentArray initialisation
start_time = time()
numbers = DocumentArray[MyDoc]([MyDoc(number=i) for i in range(n_docs)])
duration = time() - start_time
print(f"duration da init = {duration}")

# construction of list of Documents
start_time = time()
numbers = [MyDoc.construct(number=i) for i in range(n_docs)]
duration = time() - start_time
print(f"duration list construct = {duration}")

# construction of DocumentArray of Documents
start_time = time()
numbers = DocumentArray[MyDoc]([MyDoc.construct(number=i) for i in range(n_docs)])
duration = time() - start_time
print(f"duration da construct = {duration}")
```

output:
```
duration list init         =  0.035775423049926 s
duration da init           = 11.883232831954956 s
duration list construct    = 10.953930139541626 s
duration da construct      =  9.914959907531738 s
```

**Expected behavior**
Quicker.

**Comment by samsja** [comment]
@anna-charlotte it would be nice to see what kind of speed up pydantic v2 would offer.

you could do the same experiment but instead of creating a document you create a pedantic base model instance using pydantic v2.


Overall I think we cannot make this faster. That is on pydantic, and pydantic is doing nothing fancy there so that is just on python being slow for these custom things.

Could you post the results with dataclass as well ?

**Comment by JoanFM** [comment]
So we do a lot more than `Pydantic`?

**Comment by samsja** [comment]
> So we do a lot more than `Pydantic`?

we do nothing more than pydantic :thinking:

**Comment by JoanFM** [comment]
then where does the difference come from?

**Comment by JohannesMessner** [comment]
I'm not sure where else, but at least in the Document Indexes we depend on `.id` quite heavily. So how about having an id by default, but exposing a `Config` (same way pydantic has configs) to turn off id generation, as an optimization step that users can take?

Also, does this explain all the difference? That plain python dataclass is so much faster is surprising to me.

Also also, I agree that this seems looks problematic, but as long as we are faster than docarray v1 (which we seem to be) this should not block us, right?

**Comment by JohannesMessner** [comment]
We could consider using something like [this](https://github.com/thedrow/fastuuid) 🦀🦀 ? Seems to be about an order of magnitude faster than built-in, according to their benchmarks: built-in uuid4, mean time: 2.56e-6; their uuid4, mean time: 1.68e-7

**Comment by samsja** [comment]
>Also also, I agree that this seems looks problematic, but as long as we are faster than docarray v1 (which we seem to be) this should not block us, right? 

I don't think that this will block us. But it is nice to have it in mind

**Comment by samsja** [comment]
> We could consider using something like [this](https://github.com/thedrow/fastuuid) crabcrab ? Seems to be about an order of magnitude faster than built-in, according to their benchmarks: built-in uuid4, mean time: 2.56e-6; their uuid4, mean time: 1.68e-7

I am not sure that this is mature enough tbh
