### ISSUE TITLE
Dynamic class creation by "guessing" types

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1191]
We already have support for dynamic class creation, but it assumes that the types for all fields are known in advance: https://github.com/docarray/docarray/pull/1179

However, it would be nice to be able to dynamically create classes from data alone. We would have to "guess" the types by looking at the data itself (e.g. in the dict).

This would be useful, for example, for loading data from csv without having a schema beforehand. Reference: https://github.com/docarray/docarray/pull/1144

**Comment by h4shk4t** [comment]
I'd like to work on this issue

**Comment by jupyterjazz** [comment]
Hi @h4shk4t, I will take over this ticket because we want to merge it quickly. I hope you don't mind.
