### ISSUE TITLE
Incorrect type hint for `value` in `Url.validate()`

### ISSUE THREAD

**Issue by anna-charlotte** [docarray/docarray#1195]
Currently the type hint for `value` in `.validate()` of the url classes is `value: Union[T, np.ndarray, Any]`. 
It should be `value: Union[T, str, Any]` though, since we actually expect a string here, not a numpy array.

This is the case for: 
- `AudioUrl`
- `AnyUrl`
- `ImageUrl`
- `VideoUrl`
- `Url3D`

**Comment by hrik2001** [comment]
Hi, I am `riksucks#3292` from discord! Would love to take up this issue!

**Comment by Arnav131003** [comment]
Is the issue still open @anna-charlotte ?

**Comment by samsja** [comment]
fixed in https://github.com/docarray/docarray/commit/1ac70ccbc4aef1cfb659d21704aa51d07a4f5838
