### ISSUE TITLE
Multilingual text matching

### ISSUE THREAD

**Issue by GodkingRadriar** [docarray/docarray#1206]
**Is your feature request related to a problem? Please describe.**
I just started to use Docarray and I found the text search method in https://docs.docarray.org/datatypes/text/ does not support Chinese, I am wondering that does it offer multilingual support.

**Describe the solution you'd like**
Adding a multilingual support feature maybe.

**Describe alternatives you've considered**
Maybe you can give me some advice on other ways to do multilingual text retrieval via Docarray? I am really appreciated that.

**Additional context**
Thanks.

**Comment by JoanFM** [comment]
Can you try the new version of docarray, it has all changed, and maybe you can solve the problem now.
