### ISSUE TITLE
DocumentIndex: support for Elastic Search

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1209]
Implement a Document Index backed by Elasatic Search.

**References:**
- Implementation manual: https://github.com/docarray/docarray/blob/feat-rewrite-v2/docs/tutorials/add_doc_index.md
- Document Index design doc (slightly outdated, but the main ideas remain): https://lightning-scent-57a.notion.site/Document-Stores-v2-design-doc-f11d6fe6ecee43f49ef88e0f1bf80b7f
- Original PR adding Document Index base class: https://github.com/docarray/docarray/pull/1124

**Comment by asuzukosi** [comment]
@JohannesMessner if this issue is still open, I would like to work on it, since the guide for the implementation is already stated there

**Comment by Arnav131003** [comment]
Hi @JohannesMessner , I would like to take upon this issue , it would be my pleasue if you could assign it to me

**Comment by jay-bhambhani** [comment]
should we do something similar for opensearch? happy to take this on

**Comment by JohannesMessner** [comment]
Hi @jay-bhambhani, definitely happy to take that PR! I suggest you wait until @AnneYang720's ES PRs are merged so you can base your PR off of her implementation. Looking forward!

**Comment by JohannesMessner** [comment]
@jay-bhambhani ES v7 and v8 have been merged now. If you are still up for building the open search integration, we would love to see it!

**Comment by jay-bhambhani** [comment]
Excellent! I'll take a pass soon

**Comment by jay-bhambhani** [comment]
Yes! Apologies am in the middle of moving to my new house, but will jump on
this ASAP

**Comment by prd-tai-le** [comment]
Hi man @jay-bhambhani, are there any updates on this?

**Comment by jay-bhambhani** [comment]
> Hi man @jay-bhambhani, are there any updates on this?

Is this something you'd require for your work? I can revisit this ticket during the New Year. Unfortunately I will be unavailable until then

**Comment by tailtq** [comment]
@jay-bhambhani Thanks, that's cool. I use this library with OpenSearch but in version 0.21.0, it's pretty much outdated now. Sometimes, I have to monkey-patch the library to add some new mapping fields and disable the creation of the offset indices.

Hope the new version is a great update.
