### ISSUE TITLE
DocumentIndex: support for Qdrant

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1211]
Implement a Document Index backed by Qdrant.

**References:**
- Implementation manual: https://github.com/docarray/docarray/blob/feat-rewrite-v2/docs/tutorials/add_doc_index.md
- Document Index design doc (slightly outdated, but the main ideas remain): https://lightning-scent-57a.notion.site/Document-Stores-v2-design-doc-f11d6fe6ecee43f49ef88e0f1bf80b7f
- Original PR adding Document Index base class: https://github.com/docarray/docarray/pull/1124

**Comment by Arnav131003** [comment]
Hey @JohannesMessner , I would like to move on with the issue . It would be my pleasure if you assign this issue to me

**Comment by JohannesMessner** [comment]
> Hey @JohannesMessner , I would like to move on with the issue . It would be my pleasure if you assign this issue to me 

Hi @Arnav131003, thanks for your interest!
Unfortunately we already have confirmation from Kacper, who works ar Qdrant, that he will take this issue himself. I just couldn't officially assign him.

**Comment by Arnav131003** [comment]
Oh ! , Sure no problem .

**Comment by kacperlukawski** [comment]
Yeah, I'm already making some efforts to implement it. @JohannesMessner Unfortunately, I cannot assign myself. Could you please do that?

**Comment by JohannesMessner** [comment]
Done! Looking forward to the PR! And please don't forget about our implementation manual, I know it can be a bit hidden :) https://github.com/docarray/docarray/blob/feat-rewrite-v2/docs/tutorials/add_doc_index.md

**Comment by kacperlukawski** [comment]
Hi, @JohannesMessner I'll open a draft PR today in the afternoon ;) It's still in progress, and I want to provide something already partially functional. I'm sorry, but there has been a lot going on recently.
