### ISSUE TITLE
Link to join discord server has expired

### ISSUE THREAD

**Issue by asuzukosi** [docarray/docarray#1223]
**Describe the bug**
The link to join the discord server on the `README.md` file has expired, please it needs to be updated.

**Comment by JohannesMessner** [comment]
Huh that‘s weird. I‘ll tackle that first thing tomorrow, in the meantime you can find the link here: https://discord.gg/UD7K9Sfjrk

**Comment by asuzukosi** [comment]
Thank you, I was able to join now.
