### ISSUE TITLE
Cannot create Method Resolution Order

### ISSUE THREAD

**Issue by RStar2022** [docarray/docarray#1227]
# Context 
Tried running this program on VSCode but got error 
```python
class MyDoc(BaseDocument):
    title: str
    tensor: NdArray

a = MyDoc(title='hello', tensor=np.zeros(5), id = 1)
b = MyDoc(title='hello', tensor=np.zeros(5), id = 1)

assert a == b
```
Could reproduce the error when executing the program from with the following environment :
```
Windows 10 
Conda 23.1.0
Python 3.7.9
```
But could not reproduce the error above in ubuntu wsl. 
I think there's something wrong with `metaTorchAndNode` implementation.

Error :
```
Exception has occurred: TypeError
Cannot create a consistent method resolution
order (MRO) for bases type, ABCMeta
```

**Comment by JoanFM** [comment]
Hello @RStar2022 ,

are you sure to be using the branch on `feat-rewritte-v2`?

**Comment by RStar2022** [comment]
First, I tried using `main` branch, it got that error. 
After I changed the branch to `feat-rewrite-v2`, it also got the same error.

**Comment by JoanFM** [comment]
I will close it for now, as the new version has been released.

If the error persists, please do not hesitate to reopen it again
