### ISSUE TITLE
Rename variable

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1231]
# Context

we need to rename variables in DocArray.

Not all of the option are on the table yet but we know that `DocumentArray[ImageDoc]` is too verbose. We might need to shorten it to `DocArray`.

We want to find a better name for `DocumentArrayStack` as well. And maybe introduce a concept of `Documents` that is a protocol for both `DocumentArrayStack` and `DocumentArray`.

`DocList` could become a replacement name for `DocumentArray` to be more explicit on what is happening under the hood

**Comment by JoanFM** [comment]
- Alias and shorter versions with alias (DocumentArrray -> DocArray) but DocumentArray accepted but not in documentation/Readme, etc ...
