### ISSUE TITLE
add doc testing

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1233]
add `doctest` to automatically test the code examples in our docstrings

**Comment by RStar2022** [comment]
Hi @samsja I am wondering, is it better to create new file for doctest to scan all docarray files, or add doctest in each docarray file?

**Comment by samsja** [comment]
Hey @RStar2022 actually I already add the doc test but I forgot to close the issue

**Comment by samsja** [comment]
FYI it is here : https://github.com/docarray/docarray/tree/feat-rewrite-v2/tests/documentation

**Comment by RStar2022** [comment]
Okay
