### ISSUE TITLE
Try out pydantic v2

### ISSUE THREAD

**Issue by JoanFM** [docarray/docarray#1238]
Pydantic v2 makes huge under the hood changes, but the API is supposed to stay 99% the same, sou we _should_ be safe. Still, I suggest we try it out by using their alpha version in combination with docarray

**Comment by samsja** [comment]
WIP : List of incompatible things with pydantic v2:

* `from pydantic.validators import bytes_validator` does not exist anymore. [Minor]
*  `from pydantic.fields import ModelField` does not exist anymore and `validate` has a different signature [Medium]
