### ISSUE TITLE
Poetry installation stuck at pending for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by h4shk4t** [docarray/docarray#1241]
**Describe the bug**
While trying to setup docarray feat-rewrite-v2 branch with poetry, it is being indefinitely stuck at the pending status. I have removed poetry cache and config files, reinstalled poetry and run `poetry install` again but it returns the same error. 

**To Reproduce**
1. Go to the docarray folder
2. Make sure you have poetry installed
3. Run `poetry install`
4. I see the installation stuck at pending for various packages.

**Expected behavior**
It should install the required dependencies after a certain period of time.

**Screenshots**
![image](https://user-images.githubusercontent.com/34743284/225300546-add59f25-d757-4753-9cf5-e414b3b7771d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 22.04.1 LTS
 - Python version: 3.10.6
 - Docarray: feat-rewrite-v2 branch

**Comment by samsja** [comment]
Can you try the two following things :

* do `pip install attrs` instead of poetry. If this fail then it means that it is not a poetry issue but a pip attrs issue
* start a new a folder `poetry new` and then `poetry add numpy ` to see if your poetry installation that is working proprely

**Comment by h4shk4t** [comment]
1. So on running `pip install attrs` it says the requirement is already satisfied.
2. `poetry new`  works fine for a new folder, but `poetry add numpy` got stuck after creating a virtual environment with no response

**Comment by samsja** [comment]
>     2. `poetry new`  works fine for a new folder, but `poetry add numpy` got stuck after creating a virtual environment with no response

Then it is a poetry problem on your machine. Please open a ticket on https://github.com/python-poetry/poetry

**Comment by Jackmin801** [comment]
`poetry cache clear --all pypi` might work as well

**Comment by h4shk4t** [comment]
Thanks!
