### ISSUE TITLE
Make `search_field` default to empty string

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1243]
`search_field` in `find()`, `text_search()` should default to `''`.

Three reasons for that:
- In some backends (concrete example: Weaviate), the field to perform similarity search on is known a priori (or at least during schema creation time), or even a reserved name that never changes. In those cases it does not make sense for the user to pass a `search_field` argument
- If we default to `embedding` like we currently do, we make it simple for people that use our pre-defined documents (which all have an `embedding`) field, **but** we don't teach users the proper usage and flexibility that is required when they create their own schema. I think nudging users into that direction is a good thing
- Why not `Optional` and default to `None`? I think for many backends specifying a `search_field` will still be required, and making it `Optional` would send a wrong message. To me, having it non-optional but defaulting to `''` strikes a good balance. But I could be convinced otherwise.

**Comment by samsja** [comment]
@azayz assigned
