### ISSUE TITLE
chore(v2): code quality

### ISSUE THREAD

**Issue by jupyterjazz** [docarray/docarray#1255]
Let's add isort to our codebase which would check imports being alphabetically sorted.

Also, add a functionality to easily format the code while working on it, something like `make format` (calling black and isort), `make black`, `make lint`, etc.  Let's also create testing/development dependencies file consisting of above-mentioned libraries, and document the usage in CONTRIBUTING.md

**Comment by samsja** [comment]
we already have isort

**Comment by samsja** [comment]
all of this tool are already in the `pyproject.toml`

**Comment by samsja** [comment]
Not sure we need a makefile, we already have the pre-commit hook, isn'it enough ?

**Comment by samsja** [comment]
https://github.com/docarray/docarray/blob/ed4058cdc321d26d026ccbd3823277066dfafe1c/pyproject.toml#L39

**Comment by samsja** [comment]
What is not working with poetry install on mac ?

**Comment by samsja** [comment]
Ah yes the torch install is not working on mac I remember
