### ISSUE TITLE
Summary display problem

### ISSUE THREAD

**Issue by jupyterjazz** [docarray/docarray#1282]
Sometimes `doc.summary()` doesn't display all of the fields.

Example:
```python
from docarray.documents.helper import create_doc

MyDoc = create_doc('MyDoc', num=(int, ...), text=(str, ...))
doc = MyDoc(num=12, text='txt')
doc.summary()
```
In this case, field `num` is not displayed even though it exists.
```console
╭───────────────────────┬──────────────╮
│ Attribute             │ Value        │
├───────────────────────┼──────────────┤
│ text: str             │ txt          │
╰───────────────────────┴──────────────╯
```

**Comment by DevPranjal** [comment]
Hey, I faced the same issue in DocArrayV2!

I found that the summary display did not have an if clause for int/float data:

https://github.com/docarray/docarray/blob/9728bd5bfb6e82de0a89e03ee2907fdd4057a4b2/docarray/display/document_summary.py#L125-L160

Adding a simple workaround as follows fixed the issue for me:
```python
elif isinstance(value, (int, float)):
    table.add_row(col_1, str(value))
```

**Comment by jupyterjazz** [comment]
Hey @DevPranjal, nice catch! Do you want to implement this?

**Comment by DevPranjal** [comment]
Just saw a PR already made: https://github.com/docarray/docarray/pull/1287 :)

**Comment by jupyterjazz** [comment]
@DevPranjal, sorry for the misunderstanding
