### ISSUE TITLE
Fix broken Hubble DocStore tests

### ISSUE THREAD

**Issue by Jackmin801** [docarray/docarray#1301]
The Document -> Doc refactor broke the DocStore hubble tests: https://github.com/docarray/docarray/pull/1293/commits/70fde35b4800d3b024df7824588d5591c8ec025a

We should look into getting these back online.

**Comment by JoanFM** [comment]
@Tanguyabel

**Comment by IyadhKhalfallah** [comment]
I will have a look at this.
