### ISSUE TITLE
remove validation of url file extensions

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1309]
Currently, our `Url` types like `ImageUrl`, `VideoUrl` etc are performing validation based on the file extension: only file extensions of that modality are allowed.

However, that is problematic since we cannot catch all edge cases. For example, http://lh6.ggpht.com/-IvRtNLNcG8o/TpFyrudaT6I/AAAAAAAAM6o/_11MuAAKalQ/IMG_3422.JPG?imgmax=800 is a completly valid image url, but currently our validation will fail it, because the extension is not "valid".

We could fix this edge case, but the general problem remains: We are not confident that we can handle all edge cases for all data modalities, and failing validation where it should not can be a serious blocker for users.

So, we decided to remove file extension validation for all or our `Url` types.

**Comment by agaraman0** [comment]
@JohannesMessner  I will pick this up
