### ISSUE TITLE
change return type of `find_batched()` utility function

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1310]
Currently, `find_batched()` has the following signature:

```python
def find_batched(
    ...
) -> List[FindResult]:
```

In order to align with `DocumentIndex`, it should be switched to:

```python
def find_batched(
    ...
) -> FindResultBatched:
```

**TODOs:**
- move the definition of `FindResultBatched` from `index/abstract.py` to `utils/find.py`
- change the signature as described above
- fix the imports on all Document Index classes
- Probably `FindResultBatched` needs a tweak as well: `scores: np.ndarray` probably needs to be changed to allow a union of ndarray, torch.Tensor and tf.Tensor

**Comment by RStar2022** [comment]
Hi @JohannesMessner I would like to work on this issues

**Comment by JohannesMessner** [comment]
sure, take it away!

**Comment by Tuhinm2002** [comment]
Hello @JohannesMessner can I contribute to this change as it is still open

**Comment by Tuhinm2002** [comment]
Hello @JohannesMessner I have already did a pull request.. please consider my changes (this and upcoming) so I can contribute for gsoc
