### ISSUE TITLE
Improve fastapi-docarray compatibility

### ISSUE THREAD

**Issue by jupyterjazz** [docarray/docarray#1324]
Improve the way we send/receive DocArray objects with FastAPI.

### Context
Currently, DocArray objects are received as lists, so we have to construct an actual DocArray inside the function, and in case of returning, we have to convert it into a list ourselves (done in https://github.com/docarray/docarray/pull/1320)

```python
@app.post("/doc/", response_class=DocArrayResponse)
async def func(fastapi_docs: List[ImageDoc]) -> List[ImageDoc]:
    # The docs FastAPI will receive will be treated as List[ImageDoc]
    # so you need to cast it to DocArray
    docarray_docs = DocArray[ImageDoc].construct(fastapi_docs)
    ...
    # In case you want to return a DocArray, return it as a list
    return list(docarray_docs)
```

### What we want

The goal is to receive/return DocArray objects without any additional operations from the developer side. 

```python
@app.post("/doc/", response_class=DocArrayResponse)
async def func(docs: DocArray[ImageDoc]) -> DocArray[ImageDoc]:
    return docs
```

### Ways to do it

I've investigated couple of approaches, and here are the most plausible ones and the main problem I had with them: 

1. DocArray inherits from List/Sequence (draft https://github.com/docarray/docarray/pull/1316)
FastAPI still received DocArray as a List. If we fix that, this is the best way to go
2. DocArray inherits from Pydantic's GenericModel (draft https://github.com/docarray/docarray/pull/1304)
GenericModel does type-checking during runtime which introduces lots of circular imports
3. DocArray inherits from Pydantic's BaseModel (draft https://github.com/docarray/docarray/pull/1303)
BaseModel introduced couple of functions that were in conflict with our existing ones

In general, extending pydantic's classes was a bit of a headache, the first option is much cleaner.

**Comment by JoanFM** [comment]
Closed in favor of #1449
