### ISSUE TITLE
IOMixin for DocVec (to/from)

### ISSUE THREAD

**Issue by jupyterjazz** [docarray/docarray#1330]
We want to support IO functionality in `DocVec` such as from/to json, csv, bytes, etc. For example, to/from json is needed to make it FastAPI-compatible.

However, we can not use the existing IOMixin here as the logic behind DocVec is different from DocList and we'd have to overwrite some functions. 

Solution:
Create an abstract mixin containing functions that the two classes share, and for other functions create separate mixins inheriting from the abstract class

**Comment by JoanFM** [comment]
When implementing this, please make sure to habdle the case shown in #1490

**Comment by samsja** [comment]
lets not do too much abstraction here. There are no shared behavior between DocList and DocVec IO. Lets juts implement the function in both, no need for an abstract class until we can provide the same IO capacity for both
