### ISSUE TITLE
Bug in hnsw with AnyTensor

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1352]
# Context
Predefined document embedding field are not recognize by our indexer

```python
from docarray import DocList
from docarray.documents import ImageDoc
from docarray.index import HnswDocumentIndex
import numpy as np

# create some data
dl = DocList[ImageDoc](
    [
        ImageDoc(
            url="https://upload.wikimedia.org/wikipedia/commons/2/2f/Alpamayo.jpg",
            tensor=np.zeros((3, 224, 224)),
            embedding=np.random.random((128,)),
        )
        for _ in range(100)
    ]
)

# create a Document Index
index = HnswDocumentIndex[ImageDoc](work_dir='/tmp/test_index')

# index your data
index.index(dl)

# find similar Documents
query = dl[0]
results, scores = index.find(query, limit=10, search_field='embedding')
```

```cmd
  File "/home/sami/Documents/workspace/Jina/docarray2/docarray/docarray/index/backends/hnswlib.py", line 262, in _find
    docs, scores = self._find_batched(
  File "/home/sami/Documents/workspace/Jina/docarray2/docarray/docarray/index/backends/hnswlib.py", line 248, in _find_batched
    index = self._hnsw_indices[search_field]
KeyError: 'embedding'

Process finished with exit code 1
```

**Comment by AnneYang720** [comment]
The error is because `'dim': -1` in `RuntimeConfig` of [hnswlib](https://github.com/docarray/docarray/blame/feat-rewrite-v2/docarray/index/backends/hnswlib.py#L159). 
It's changed in [this commit](https://github.com/docarray/docarray/commit/41484bc0df471ced66e759a90fe4e9ba9b291d72).
According to the logger info, I think we need to specify the dimensionality in this case.

```python
import numpy as np

from docarray import DocList
from docarray.documents import ImageDoc
from docarray.index import HnswDocumentIndex
from docarray.typing import NdArray


class MyImageDoc(ImageDoc):
    embedding: NdArray[128]


# create some data
dl = DocList[ImageDoc](
    [
        ImageDoc(
            url="https://upload.wikimedia.org/wikipedia/commons/2/2f/Alpamayo.jpg",
            tensor=np.zeros((3, 224, 224)),
            embedding=np.random.random((128,)),
        )
        for _ in range(100)
    ]
)

# create a Document Index
index = HnswDocumentIndex[MyImageDoc](work_dir='./tmp/test_index')

# index your data
index.index(dl)

# find similar Documents
query = dl[0]
results, scores = index.find(query, limit=10, search_field='embedding')
```

**Comment by AnneYang720** [comment]
I found another possible issue. The dimension has to be an integer. The following example cannot work:
```python
class MyImageDoc(ImageDoc):
    tensor: NdArray[3,16,16]
    # should be tensor: NdArray[768]
```

The `tensor` value also needs to be flattened. 
```python
dl = DocList[ImageDoc]([ImageDoc(tensor=np.ones((3, 16, 16)).flatten()) for _ in range(100)])
```

Should we add some auto conversion for multi-dimensional tensors?
@samsja @JohannesMessner

**Comment by JoanFM** [comment]
I think `multidimensional` tensors should not work, let's not do  magic

**Comment by samsja** [comment]
agree with @JoanFM no need to take care of the `multidimensional` .

Okay I see the problem, so this means we cannot really use our predefined documents with vector database right ? Because we need to somehow define the embedding field size

**Comment by AnneYang720** [comment]
> agree with @JoanFM no need to take care of the `multidimensional` .
> 
> Okay I see the problem, so this means we cannot really use our predefined documents with vector database right ? Because we need to somehow define the embedding field size

Yes, we need to define the dimensionality for hnswlib. 

But the default value for elasticsearch is `'dims': 128` [here](https://github.com/docarray/docarray/blob/0cc9e64e6c17ceec1b0685ba3fc00d5f083a5ada/docarray/index/backends/elastic.py#L235). Should I change it as well, to make this rule apply to every database.

**Comment by JohannesMessner** [comment]
Just to clarify:
- You *can* insert pre-defined docs into a Document Index
- You *cannot* use a predefined doc as the schema for a Document Index. But this is not because of `AnyTensot`, this is just generally bc predefined docs do not have a dimensionality annotation
- You *can* use `AnyTensor` (or any other union of tensors) *both* in the data you are indexing, *and* in the schema of the Document Index. To dot that, you need to specify the dimensionality in the `= Field(...)` default value

**Comment by samsja** [comment]
makes sense, would be nice to add it to documentation somewhere !
