### ISSUE TITLE
Weaviate: Add more robust method to detect existing index

### ISSUE THREAD

**Issue by hsm207** [docarray/docarray#1357]
**Is your feature request related to a problem? Please describe.**
An index should be considered as exist when there is a schema with the exist name and properties.

**Describe the solution you'd like**
Use the client's `exists` instead of `contains` method to detect an existing index name.

**Describe alternatives you've considered**
NA

**Additional context**
Wait for weaviate/weaviate-python-client#232 to be implemented

**Comment by JoanFM** [comment]
Hello, @hsm207 , 

Are you actively working on this ticket?

**Comment by hsm207** [comment]
@JoanFM not at the moment. I'll try to get this done on Friday.
