### ISSUE TITLE
When does ElasticSearch7 support

### ISSUE THREAD

**Issue by yuanjie-ai** [docarray/docarray#1374]
When does ElasticSearch7 support

**Comment by JohannesMessner** [comment]
Hey! We will be releasing today (if nothing comes up), including ES v7 support

**Comment by yuanjie-ai** [comment]
Do you have any relevant use-documents
`docarray.index.backends.elasticv7.ElasticV7DocIndex`

**Comment by JohannesMessner** [comment]
You can check out the docs [here](https://docs.docarray.org/user_guide/storing/index_elastic/). ES v7 and v8 share the same API through docarray, so the documentation is valid for both.
