### ISSUE TITLE
bug: protobuf not installed with docarray[common]

### ISSUE THREAD

**Issue by alexcg1** [docarray/docarray#1420]
I was trying something like:

```python
docs.push('file://books.docarray')
```

And I got the following error:

```
ImportError: The following required library is not installed: google.protobuf 
To install all necessary libraries, run: `pip install "docarray[common]"`
```

After running `pip install docarray[common]` and retrying I get the same error. `pip list | grep protobuf` returns nothing.

**Comment by samsja** [comment]
@anna-charlotte can u take a look at the pip error message ? I think common does not exist anymore it should say pip install docarray[protobuf]

**Comment by samsja** [comment]
> After installing `protobuf` and re-running, script seems to work fine, but no file is saved in the project directory.
> 
> However, `books.docs` (not `books.docarray`) is saved in `~/.cache/docarray`

can u put a reproducible code example ?

**Comment by alexcg1** [comment]
[Code example](https://github.com/alexcg1/docarray-v2-books/blob/main/app.py)

**Comment by samsja** [comment]
You cannot put file extension in the push pull. Like for push pull to Jina AI cloud. Though we should probably raise an error instead of just removing the extension

**Comment by alexcg1** [comment]
This shouldn't be closed, File still gets saved to` ~/.cache/docarray`, not `./`

**Comment by alexcg1** [comment]
I would say parse the path. `file://foo` would always refer to `./foo` everywhere else I've seen it

**Comment by samsja** [comment]
> This shouldn't be closed, File still gets saved to ~/.cache/docarray, not ./
this is expected as the default behavior.

The goal is to have the same experience with push pull to cloud that push pull locally. This means that you need to save, at least by default, into a common cache. If you just want to save to a file use `save_bynari`

**Comment by alexcg1** [comment]
fwiw @scott-martens thinks `file://` would normally save to filesystem root

**Comment by samsja** [comment]
@Jackmin801 FYI

**Comment by samsja** [comment]
cache makes no sense for a protocl

**Comment by samsja** [comment]
I still don't understand why you are not using `save_binary`.

To me push pull is if you want to sync some data between two people on the same computer for instance, in this case you want to use cache as default.

**Comment by alexcg1** [comment]
Eh, I'll just use `save_binary` then. Just the `push/pull` `file://` thing seems weird

**Comment by JoanFM** [comment]
What is the status here?

**Comment by samsja** [comment]
this is the expected behavior. Closing the issue
