### ISSUE TITLE
Bug: Serializing TorchTensor with grad fails

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1438]
**Description:**
When a `TorchTensor` requires grad it cannot be serialized to JSON.
This is particularly bad because:
-  outputs of pytorch models require grad
- FastAPI serilaizes to JSON
-> model serving is b0rked

**How to reproduce:**
```python
from docarray import BaseDoc
from docarray.typing import TorchTensor
import torch

class MyDoc(BaseDoc):
    tens: TorchTensor

t1 = torch.rand(512, requires_grad=True)
doc = MyDoc(tens=t1)
doc.json()
```
```bash
TypeError: Type is not JSON serializable: TorchTensor
```

But the following works:
```python
from docarray import BaseDoc
from docarray.typing import TorchTensor
import torch

class MyDoc(BaseDoc):
    tens: TorchTensor

t1 = torch.rand(512, requires_grad=True)
doc = MyDoc(tens=t1.detach())
doc.json()
```

**TODO**:
- Fix this, probably by calling `detach()` in the serialization logic
- check if other serialization options are also affected
- what about tensorflow?

**Comment by JoanFM** [comment]
@makram93 u can assign urself here

**Comment by makram93** [comment]
@JohannesMessner pinging here so you can assign it to me.
