### ISSUE TITLE
Bug: Type coercion from torch to numpy does not work

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1439]
**Description:**
casting a TorchTensor NdArray fails

**How to reproduce:**
```python
from docarray import BaseDoc
from docarray.typing import NdArray
import torch

class MyDoc(BaseDoc):
    tens: NdArray

t1 = torch.rand(512)
doc = MyDoc(tens=t1)
```
```bash
  Expected a numpy.ndarray compatible type, got <class 'torch.Tensor'> (type=value_error)
```

**TODO**:
- Fix this in the `validate` function of `NdArray`
- what about coercions to/from tf? do we have tests for this?

**Comment by JohannesMessner** [comment]
Update: the easy way of fixing this produces unwanted side effects. Basicaly, if we make coercion to np too powerful, then it will break `AnyTensor == Union[NdArray, TorchTensor, TensorFlowTensor]`, since it would cast everything to np. This is due to how pydantic resolves validation for unions.

The only solution i see here is defining our own Union with our own validation rules, and then re-defining AnyTensor in terms of that.
This is a bit more involved than the naive fix, so we de-emphasize that for now.

**Comment by makram93** [comment]
pining so that you can assign it to me!
