### ISSUE TITLE
add json-array to save binaries

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1442]
# Context

DocList.save_binary does not support json protocol. It should IMO

**Comment by IyadhKhalfallah** [comment]
I will take this one

**Comment by RStar2022** [comment]
Hey @samsja @JoanFM  I have been working on this issue since yesterday, and I was unaware that it should be assigned.

**Comment by samsja** [comment]
that is fine then you can continue to work on it @RStar2022 . @IyadhKhalfallah lets sync together on which ticket you could work on

**Comment by samsja** [comment]
@RStar2022 feel free to drop a comment when you start working on something btw ! So that we are aware of it and it don't get assigned

**Comment by JoanFM** [comment]
@RStar2022 no worries, assigned to you
