### ISSUE TITLE
add DocArray as an option to do SemanticSearch in GPTCache

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1448]
We could put our InMemoryIndex and HNSWLib here
 https://github.com/zilliztech/GPTCache

**Comment by jupyterjazz** [comment]
They already support hnswlib

I'm working to add in_memory index
draft pr - https://github.com/jupyterjazz/GPTCache/pull/1

**Comment by JoanFM** [comment]
> They already support hnswlib
> 
> I'm working to add in_memory index draft pr - [jupyterjazz/GPTCache#1](https://github.com/jupyterjazz/GPTCache/pull/1)

Anyway, let's add one with docarray that can support hnswlib combined with SQLIte

**Comment by JoanFM** [comment]
We can do in separate pRs

**Comment by jupyterjazz** [comment]
https://github.com/zilliztech/GPTCache/pull/351
