### ISSUE TITLE
docs: check migration guide

### ISSUE THREAD

**Issue by anna-charlotte** [docarray/docarray#1451]
The `migration guide` in the docs has been merged without final check by team tech content to be included in the release. Therefore we need a final check here

**Comment by samsja** [comment]
I think @alexcg1 did one review of the migration guide (in term of typo etcc) the day after we released. @alexcg1 if you confirm that you did we can close this ticket

**Comment by alexcg1** [comment]
I definitely checked it and made corrections. https://github.com/docarray/docarray/commits/main/docs/migration_guide.md
