### ISSUE TITLE
Storing different documents in weaviate does not work because the index_name is not inferred from the BaseDoc subclass' name

### ISSUE THREAD

**Issue by hugocool** [docarray/docarray#1455]
Storing two different types of documents in weaviate does not work.
I dont understand the API design here, is this intentional?

for example, lets assume I want to do a multilingual search, and have to use different embedding models to achieve this, or lets take the example from the documentation and add a different class, this will result in an error.
 Example:
```python
import numpy as np
from pydantic import Field
from docarray import BaseDoc, DocList
from docarray.typing import NdArray
from docarray.index.backends.weaviate import WeaviateDocumentIndex

# Define a document schema
class Document(BaseDoc):
    text: str
    embedding: NdArray[2] = Field(
        dims=2, is_embedding=True
    )  # Embedding column -> vector representation of the document
    file: NdArray[100] = Field(dims=100)

# define a book schema
class Book(BaseDoc):
    title: str
    embedding: NdArray = Field( is_embedding=True) 

# Make a list of 3 docs to index
docs = DocList[Document]([
    Document(
        text="Hello world", embedding=np.array([1, 2]), file=np.random.rand(100), id="1"
    ),
    Document(
        text="Hello world, how are you?",
        embedding=np.array([3, 4]),
        file=np.random.rand(100),
        id="2",
    ),
    Document(
        text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut",
        embedding=np.array([5, 6]),
        file=np.random.rand(100),
        id="3",
    ),
])

books = DocList[Book]([
    Book(
        title="Harry Potter", embedding=np.array([1, 2,3]), id="1"
    ),
    Book(
        title="Lords of the rings", embedding=np.array([3, 4,5]), id="2"
    ),
])

batch_config = {
    "batch_size": 20,
    "dynamic": False,
    "timeout_retries": 3,
    "num_workers": 1,
}

runtimeconfig = WeaviateDocumentIndex.RuntimeConfig(batch_config=batch_config)
dbconfig = WeaviateDocumentIndex.DBConfig(
    host="http://localhost:8080"
) 
store = WeaviateDocumentIndex[Document](db_config=dbconfig)
store.configure(runtimeconfig)  # Batch settings being passed on
store.index(docs)

store = WeaviateDocumentIndex[Book](db_config=dbconfig)
store.configure(runtimeconfig)  # Batch settings being passed on
store.index(books)
```

This gives:
```
---------------------------------------------------------------------------
UnexpectedStatusCodeException             Traceback (most recent call last)
[/tmp/ipykernel_22411/2065625298.py](https://vscode-remote+ssh-002dremote-002baimwel-002dec2.vscode-resource.vscode-cdn.net/tmp/ipykernel_22411/2065625298.py) in ()
     56 runtimeconfig = WeaviateDocumentIndex.RuntimeConfig(batch_config=batch_config)
     57 
---> 58 store = WeaviateDocumentIndex[Book](db_config=dbconfig)
     59 store.configure(runtimeconfig)  # Batch settings being passed on
     60 store.index(docs)

[~/isco-labeling-tool/.venv/lib/python3.9/site-packages/docarray/index/backends/weaviate.py](https://vscode-remote+ssh-002dremote-002baimwel-002dec2.vscode-resource.vscode-cdn.net/home/ec2-user/isco-labeling-tool/notebooks/~/isco-labeling-tool/.venv/lib/python3.9/site-packages/docarray/index/backends/weaviate.py) in __init__(self, db_config, **kwargs)
    110         self._set_embedding_column()
    111         self._set_properties()
--> 112         self._create_schema()
    113 
    114     def _set_properties(self) -> None:

[~/isco-labeling-tool/.venv/lib/python3.9/site-packages/docarray/index/backends/weaviate.py](https://vscode-remote+ssh-002dremote-002baimwel-002dec2.vscode-resource.vscode-cdn.net/home/ec2-user/isco-labeling-tool/notebooks/~/isco-labeling-tool/.venv/lib/python3.9/site-packages/docarray/index/backends/weaviate.py) in _create_schema(self)
    217             )
    218         else:
--> 219             self._client.schema.create_class(schema)
    220 
    221     @dataclass

[~/isco-labeling-tool/.venv/lib/python3.9/site-packages/weaviate/schema/crud_schema.py](https://vscode-remote+ssh-002dremote-002baimwel-002dec2.vscode-resource.vscode-cdn.net/home/ec2-user/isco-labeling-tool/notebooks/~/isco-labeling-tool/.venv/lib/python3.9/site-packages/weaviate/schema/crud_schema.py) in create_class(self, schema_class)
    180         # validate the class before loading
...
--> 708             raise UnexpectedStatusCodeException("Create class", response)
    709 
    710     def _create_classes_with_primitives(self, schema_classes_list: list) -> None:

UnexpectedStatusCodeException: Create class! Unexpected status code: 422, with response body: {'error': [{'message': "Name 'Document' already used as a name for an Object class"}]}.
```

This happens because in `docarray/index/backends/weaviate.py` on line 210:
```
schema["class"] = self._db_config.index_name
```

So the class that is being added to weaviate (the table) is named after the _db_config's index_name, instead of the name of the schema class.

One can solve this in this (quite hacky) manner:
```
dbconfig = WeaviateDocumentIndex.DBConfig(
    host="http://localhost:8080",
    index_name=books.doc_type.__name__
)
store = WeaviateDocumentIndex[Book](db_config=dbconfig)
store.configure(runtimeconfig)  # Batch settings being passed on
store.index(books)
```

or use the `Book.__name__` property.

Anyway, my proposed solution would be to use the name of the class, and not some undocumented name in the db_config, this behaviour is quite unexpected tbh.

**Comment by hsm207** [comment]
> Anyway, my proposed solution would be to use the name of the class, and not some undocumented name in the db_config

`index_name` is documented. See section 2.2 in the [docs](https://docs.docarray.org/user_guide/storing/index_weaviate/)

**Comment by hugocool** [comment]
What I meant by undocumented is the fact that you would expect the class/table in weaviate to be named after data class you are actually storing, and not the index name in the dan config.

So for example if you use any other ORM, like SQLModel (which is also based on pydantic), it you make a Book class, and commit an instantiated version of it, the table is named book, after the name of the class.
This is the case in every ORM.

So I wonder why DocArray is doing it differently. Is this on purpose?
And if yes, why?

Has your user research indicated that users prefer to name their table entries after that en config?

And coincidentally now be constrained in in which tables they can query based on with which db config settings they initiated the client object with.

This seems confusing to me, and that behavior is not properly documented if it is intended.

It just so happens that the default value for db config index name is “Document” and in the documentation  the example class is also called ”Document”.
As such, one is led to believe that that the class in the weaviate database is called “Document” because that is the name of the Object. However, this is not at all the, instead the name is derived from some buried parameter is the db config, which has a default value of “Document”.

So I would propose to remedy this confusing design error. If you want me to write an implementation and do a PR I will.

Please advise.

**Comment by hsm207** [comment]
I think @JohannesMessner is the best person to explain the design decisions the team took.

From my point of view, the trade off of your proposed solution is that it won't work in this use case:

```
train_store = WeaviateDocumentIndex[TextDoc]()
test_store = WeaviateDocumentIndex[TextDoc]()
```

i.e. a user would like to train an ML model and want to store their training and test set separately.

**Comment by hugocool** [comment]
I would in that case subclass the main class into a train and test class.
This would result in different tables, since the names of the subclasses would be different.
While keeping the code DRY.

And (at least in SQL ORMS) these could be related to the main class if you so desire.

**Comment by JoanFM** [comment]
I think you have a point here @hugocool,

but at the same time I do not want the user to be forced to subclass if they want to store in different indexes. I believe the best would be to make the DBConfig default index_name to None. And override this with the name of the class of the Document if not present but still give priority to the DBConfig index name.

Would this work for you?

**Comment by JohannesMessner** [comment]
The idea behind this design decision was essentially about separation of concerns.
The class/Document is intended to specify the schema of the database table/collection; what that table/collection is called is a different issue imo. There are use cases where one wants to use the same schema but spread over different tables, the one that @hsm207 mentions is a good example.

I think in projects like SQLModel this is less of a consideration, since there pydantic models are exclusively intended to model database interactions, making it natural to create a new class for a new table.
In our case, Documents are also used to represent and hold data that, for example, flows though a neural network, or is used in some other way.
So requiring different Document classes for different DB tables would then also require the user to use different Document classes in other parts of their business logic. This is not what we want.

I think @JoanFM's proposal is a good compromise. We would have to do:
- Implement default behaviour s.t. table/collection name is taken from document class name. I think we would have to do that for every backend individually
- update the howto about adding a new DocumentIndex to reflect this behaviour as the standard specification

I'm happy to assign this to anyone that is willing to take it :)

**Comment by hugocool** [comment]
I want to do the exact thing you describe, use basically the same model but for different embedding model. Since in my use case, i would have EnglischBook, ThaiBook, FinnishBook, and all these language require specific paraphrasing models for search to function properly (since multilingual models offer very poor performance in underserved languages).
So I was using a Class Factory pattern to create the subclasses for each language.

This worked like expected in the ORM I use, so since DocArray is like an ORM for these vector databases I expected the same behaviour there too.

Anyway, I really appreciate the work you guys are putting into this project. I love projects like SQLModel, Notional, pydantic-yaml, and DocArray. 
These best practice interfaces are a really good idea and make everybodies lives a lot easier.
Thanks guys, and thanks for the discussion, im really happing you guys are so involved and responsive to feedback!
