### ISSUE TITLE
docs: hnswlib cosine distance

### ISSUE THREAD

**Issue by anna-charlotte** [docarray/docarray#1475]
Specify in the documentation of the `HnswLibDocIndex` that 'cosine' refers to cosine distance, not cosine similarity.
In the hnswlib documentation they claim it to be similarity, but it actually is distance. I opened an [issue](https://github.com/nmslib/hnswlib/issues/456#issuecomment-1521118534) on their side, and they will change it in their documentation.

**Comment by JoanFM** [comment]
This will close #1473
