### ISSUE TITLE
Error - Cannot import name 'Document' from 'docarray'

### ISSUE THREAD

**Issue by ranjancse26** [docarray/docarray#1484]
Followed the below steps

1. !pip install docarray
2. Executing the below statement leads to error

from docarray import Document, DocumentArray

ImportError                               Traceback (most recent call last)
[<ipython-input-2-79d7b7d8f9e4>](https://localhost:8080/#) in <cell line: 2>()
      1 # Importing necessary dependencies
----> 2 from docarray import Document, DocumentArray

ImportError: cannot import name 'Document' from 'docarray' (/usr/local/lib/python3.10/dist-packages/docarray/__init__.py)

**Comment by ranjancse26** [comment]
/reopen

Sorry, I am referring to the same latest documentation. However, I couldn't get it working on Google Colab. Here's the sample code I am trying to run. The fundamental thing that I am struggling to run on Colab.

`from docarray import Document
Document(text='hello, world.')`

**Comment by ranjancse26** [comment]
/reopen

Sorry, I am referring to the same latest documentation. However, I couldn't get it working on Google Colab. Here's the sample code I am trying to run. The fundamental thing that I am struggling to run on Colab.

`from docarray import Document
Document(text='hello, world.')`

**Comment by ranjancse26** [comment]
/reopen

Sorry, I am referring to the same latest documentation. However, I couldn't get it working on Google Colab. Here's the sample code I am trying to run. The fundamental thing that I am struggling to run on Colab.

`from docarray import Document
Document(text='hello, world.')`

**Comment by JoanFM** [comment]
Can you point exactly to what part of Documentation you are referring to?

**Comment by ranjancse26** [comment]
Here are the steps.

1. Open https://docs.docarray.org/
2. Install docarray by following the install guide - https://docs.docarray.org/get-started/install/
3. Navigate to Data Types -> Text by clicking on https://docs.docarray.org/datatypes/text/
4. Try to run the following code. And you will see the failure for importing the Document.

`
from docarray import Document
Document(text='hello, world.')
`

5. Please take a look into the following sample - https://github.com/docarray/docarray/blob/main/tests/integrations/predefined_document/test_text.py 

You will see the right import for document.

`
from docarray import BaseDoc
from docarray.documents import TextDoc
`

**Comment by JoanFM** [comment]
Hello @ranjancse26 ,

Somehow we are linking to the wrong old legacy Documentation, we will solve this ASAP.

**Comment by JoanFM** [comment]
I will fix the link under the new issue #1500

**Comment by JoanFM** [comment]
The proper documentation link is this one  https://docs.docarray.org/

**Comment by ranjancse26** [comment]
Thanks for the update @JoanFM  It looks good!
