### ISSUE TITLE
Redundant parameter `search_field` in weaviate hybrid search

### ISSUE THREAD

**Issue by violenil** [docarray/docarray#1504]
The `search_field` parameter seems to be redundant in the hybrid search query on a Weaviate document index, since the text search will search all fields of the object and no specific text field may be supplied. However, when not supplied, the following error occurs:

<img width="821" alt="Screenshot 2023-05-08 at 11 45 20" src="https://user-images.githubusercontent.com/55404563/236793299-5c74e77c-b6b3-4efc-b3e1-c9025dcde2fc.png">

Although the [documentation](https://docs.docarray.org/user_guide/storing/index_weaviate/) also explains that this parameter is `necessary but has no effect`, since all text fields will be searched by the hybrid query, it seems there should be no requirement to pass a `None` value here.

 <img width="867" alt="Screenshot 2023-05-08 at 11 48 24" src="https://user-images.githubusercontent.com/55404563/236793705-ee0229f2-c91c-4907-91e4-ef3e84ddb4e9.png">

**Comment by hsm207** [comment]
weaviate can now support searching in specific field(s) (the BM25 part) when doing hybrid search (see this [issue](https://github.com/weaviate/weaviate/issues/2747)). We should update the implementation in docarray accordingly.

**Comment by JoanFM** [comment]
Hey @hsm207 , maybe u can create a ticket for this change?

**Comment by AnneYang720** [comment]
Hi @hsm207 , I checked the lastest code of weaviate python client. It seems class `Hybrid` still doesn't have `properties` [here](https://github.com/weaviate/weaviate-python-client/blob/main/weaviate/gql/get.py#L49).  Like in [weaviate go](https://github.com/weaviate/weaviate/pull/2968/files#diff-c323c8a4ee0021aaaa831b2c8d47abdf20b1722fc01e94f877a46413ccbe16c8), I guess this should be changed to:

```python
@dataclass
class Hybrid:
    query: str
    alpha: float
    vector: List[float]
    properties: Optional[List[str]]

    def __str__(self) -> str:
        ret = f'query: "{util.strip_newlines(self.query)}"'
        if self.vector is not None:
            ret += f", vector: {self.vector}"
        if self.alpha is not None:
            ret += f", alpha: {self.alpha}"
        if self.properties is not None and len(self.properties) > 0:
            props = '","'.join(self.properties)
            ret += f', properties: ["{props}"]'

        return "hybrid:{" + ret + "}"
```

**Comment by JohannesMessner** [comment]
I think what we should do is simply make it such that the user doesn't hate to pass `search_field=None` since it doesn't do anything. So the argument should be made optional

**Comment by AnneYang720** [comment]
I found a possible issue that the `search_field` of `_text_search()` in weaviate doesn't have any effect. For example:
```python
from pydantic import Field

from docarray import BaseDoc
from docarray.index.backends.weaviate import WeaviateDocumentIndex

class Document(BaseDoc):
    text: str = Field()
    text2: str = Field()

texts = ["lorem ipsum", "dolor sit amet", "consectetur adipiscing elit"]
texts2 = ["dolor sit amet", "lorem ipsum", "consectetur adipiscing elit"]

docs = [
    Document(id=str(i), text=text, text2=text2)
    for i, (text, text2) in enumerate(zip(texts, texts2))
]

index = WeaviateDocumentIndex[Document]()
results = index.text_search(query='ipsum', search_field='text')
print(len(results)) # 2
```
The `len(result)` should be 1 in my understanding. Is this the expected behavior? @hsm207

**Comment by JohannesMessner** [comment]
Afaik the search_field doesn't have any effect in any of the weaviate methods since it is already declared at schema creation time what field to search on. Can you confirm @hsm207?

**Comment by hsm207** [comment]
> Hi @hsm207 , I checked the lastest code of weaviate python client. It seems class `Hybrid` still doesn't have `properties` [here](https://github.com/weaviate/weaviate-python-client/blob/main/weaviate/gql/get.py#L49)

@AnneYang720 I'm sorry, I forgot to verify if clients have implemented this feature. Support for adding properties in the hybrid search is coming soon: https://github.com/weaviate/weaviate-python-client/pull/319

> The len(result) should be 1 in my understanding. Is this the expected behavior? @hsm207

@AnneYang720 I agree, it should be 1. The implementation really does look at the supplied search_field (see [here](https://github.com/docarray/docarray/blob/20fdcd27b786f7fea9ab4bc4ee5bbbd244ba66f0/docarray/index/backends/weaviate.py#L588-L604)). Did the docarray team made some changes to the interface since it was release?

Your code snippet is very similar to the test case I wrote (see [here](https://github.com/docarray/docarray/blob/20fdcd27b786f7fea9ab4bc4ee5bbbd244ba66f0/tests/index/weaviate/test_index_get_del_weaviate.py#L46-L57) and [here](https://github.com/docarray/docarray/blob/20fdcd27b786f7fea9ab4bc4ee5bbbd244ba66f0/tests/index/weaviate/test_index_get_del_weaviate.py#L212-L214)). In that test, I asked for 3 documents but only got 1, as expected. This test still passes in the CI, doesn't it?

> Afaik the search_field doesn't have any effect in any of the weaviate methods since it is already declared at schema creation time what field to search on. Can you confirm @hsm207?

@JohannesMessner That's incorrect. When we built this initially, the search_field is meant to have effect on text_search only and no effect on hybrid search.

**Comment by hsm207** [comment]
@AnneYang720 i found the reason:

instead of :

```
results = (
            self._client.query.get(index_name, self.properties)
            .with_bm25(bm25)
            .with_limit(limit)
            .with_additional(["score", "vector"])
            .do()
        )
```

it should be:

```
results = (
            self._client.query.get(index_name, self.properties)
            .with_bm25(**bm25)
            .with_limit(limit)
            .with_additional(["score", "vector"])
            .do()
        )
```

i.e. we need to unpack the dict that gets passed to `with_bm25`.

Can you do the fix?

**Comment by AnneYang720** [comment]
> the weaviate python client now supports search field in hybrid search (see https://github.com/weaviate/weaviate-python-client/releases/tag/v3.18.0)

I'll open a new PR for this.

**Comment by JoanFM** [comment]
> the weaviate python client now supports search field in hybrid search (see https://github.com/weaviate/weaviate-python-client/releases/tag/v3.18.0)

@hsm207 could you open a PR to add this in a new PR?
