### ISSUE TITLE
Preventing the embeddings from getting returned as a result of a search query.

### ISSUE THREAD

**Issue by hugocool** [docarray/docarray#1528]
When i use the weaviate client directly, i can limit what is being returned from a query, such that the embeddings (which i dont need anymore once the desired objects have been found) are not getting returned.

However, when using DocArray, this is not possible due to the implementation of the QueryBuilder class.

Should we add an option to limit what is being queried, and would you like to model the API after other ORMs, such as SQLAlchemy?

**Comment by JohannesMessner** [comment]
Hi @hugocool, you are right, this is currently not possible. But thanks for raising interest in this! I think in principle we should be able to do this, but we need to look into it a bit more. We will report back! @hsm207 maybe you also have input on this?

**Comment by JoanFM** [comment]
Hey @hugocool ,

We will take this feature into account and see what we can do for this.

As per the ORM question. I am not exactly sure what you mean by that, but in my opinion, why they are quite similar, DocArray is not exactly the same as `SQLAlchemy` and could be considered more suited for more unstructured data and not so much aimed to work with traditional databases. 

But it would be interesting what exact API considerations you have in mind and we can discuss them at each step.

**Comment by hsm207** [comment]
@JohannesMessner it is possible do this now by writing the raw graphql query. e.g. see this [test](https://github.com/docarray/docarray/blob/29c2d23a618704e9ed13108c754e09c6ef053a93/tests/index/weaviate/test_index_get_del_weaviate.py#L331-L347)

**Comment by JoanFM** [comment]
@hsm207 would you implement a new feature or add this somewhere in documentation?

**Comment by hsm207** [comment]
@JoanFM this feature is already documented in the [docs](https://docs.docarray.org/user_guide/storing/index_weaviate/) (see section 5.4).
