### ISSUE TITLE
automatic release notes

### ISSUE THREAD

**Issue by jupyterjazz** [docarray/docarray#1543]
Currently, we fill PR descriptions for release notes by hand. 
Would be nicer if PR descriptions included a separate section (short summary) that we could automatically put into the release note.
Releases would require less effort, and also PRs will become more informative. 

**Definition of Done**
- [ ] Modify the PR template to ask for a short summarization of the PR as the last part of the description (may require a separate guidelines file, explaining what/how to write in each case - bug, feat, refactor..), make sure that it can be easily extracted
- [ ] Modify the workflow that creates release notes to extract the release text and include it in the note

**Comment by JoanFM** [comment]
We have internally a Release Note procedure that involves handcrafting the notes thst has resulted in high quality notes. I would not change this at this moment

**Comment by jupyterjazz** [comment]
@JoanFM, with this approach quality will not be compromised. What will change is less effort on the release note and more informative PRs.

**Comment by JoanFM** [comment]
I know it will not be compromised but even improved. My problem is the effort to deliver this
