### ISSUE TITLE
Indexing field of DocList type (=subindex)is not yet supported.

### ISSUE THREAD

**Issue by munish0838** [docarray/docarray#1544]
I am creating database of the following format, but unable to index/search
User 
   -- Folder (multiple folders)
       -- Document (multiple documents)
           -- Sentences ( document split into sentences)

For the datastore, I get the error `Indexing field of DocList type (=subindex)is not yet supported.` when using HNSWLIB 

1. What alternative datastore can I use that currently support the case, or what alternate strategy I could use to implement the same
2. Is searching in sub-sub index possible? Is there a direct function or alternate strategy to use as of now?
3. I want to search for relevant sentences from all of the documents in one folder at once, so how can I search through all of them at once

**Comment by JoanFM** [comment]
Hello @munish0838 ,

We are about to release the feature to enable subindex search. I hope this will fix the issue.

**Comment by JoanFM** [comment]
This is released in 0.32.0 version
