### ISSUE TITLE
Url types are not aware of extension during validation

### ISSUE THREAD

**Issue by alaeddine-13** [docarray/docarray#1555]
Url types do not perform validation on the url extension. For instance, if a url has extension to an audio file (.wav), ImageURL can still accept it.

in the screenshot below, when a field is defined like this `item: Union[ImageUrl, AudioUrl, str]`, when it is initialized like this : MyClass(item='link to audio') it will be validated against a ImageUrl. This is because ImageUrl considers a .wav file a valid image

![Image](https://github.com/docarray/docarray/assets/15269265/81369255-f062-48b6-953b-42ceea4380e5)

**Comment by makram93** [comment]
pinging to pick this up
