### ISSUE TITLE
Not able to index when using List[str] in custom document class

### ISSUE THREAD

**Issue by lazyhope** [docarray/docarray#1557]
System: `macOS 13.3.1`
Python version: `3.11.0`
IPython version: `8.10.0`

In the latest docarray version, when building hnsw index from the following simple document class:
```python
from docarray import BaseDoc
from docarray.index import HnswDocumentIndex

class MyDoc(BaseDoc):
    test: List[str]

index = HnswDocumentIndex[MyDoc]()
```
The following error will pop up:
```
File ~/miniconda3/envs/test/lib/python3.11/site-packages/docarray/index/backends/hnswlib.py:76, in HnswDocumentIndex.__init__(self, db_config, **kwargs)
     73 if db_config is not None and getattr(db_config, 'index_name'):
     74     db_config.work_dir = db_config.index_name.replace("__", "/")
---> 76 super().__init__(db_config=db_config, **kwargs)
     77 self._db_config = cast(HnswDocumentIndex.DBConfig, self._db_config)
     78 self._work_dir = self._db_config.work_dir

File ~/miniconda3/envs/test/lib/python3.11/site-packages/docarray/index/abstract.py:111, in BaseDocIndex.__init__(self, db_config, subindex, **kwargs)
    109 self._runtime_config = self.RuntimeConfig()
    110 self._logger.info('Runtime config created')
--> 111 self._column_infos: Dict[str, _ColumnInfo] = self._create_column_infos(
    112     self._schema
    113 )
    114 self._is_subindex = subindex
    115 self._subindices: Dict[str, BaseDocIndex] = {}

File ~/miniconda3/envs/test/lib/python3.11/site-packages/docarray/index/abstract.py:880, in BaseDocIndex._create_column_infos(self, schema)
    873 """Collects information about every column that is implied by a given schema.
    874
    875 :param schema: The schema (subclass of BaseDoc) to analyze and parse
    876     columns from
    877 :returns: A dictionary mapping from column names to column information.
    878 """
    879 column_infos: Dict[str, _ColumnInfo] = dict()
--> 880 for field_name, type_, field_ in self._flatten_schema(schema):
    881     # Union types are handle in _flatten_schema
    882     if issubclass(type_, AnyDocArray):
    883         column_infos[field_name] = _ColumnInfo(
    884             docarray_type=type_, db_type=None, config=dict(), n_dim=None
    885         )

File ~/miniconda3/envs/test/lib/python3.11/site-packages/docarray/index/abstract.py:860, in BaseDocIndex._flatten_schema(cls, schema, name_prefix)
    856     else:
    857         raise ValueError(
    858             f'Union type {t_} is not supported. Only Union of subclasses of AbstractTensor or Union[type, None] are supported.'
    859         )
--> 860 elif issubclass(t_, BaseDoc):
    861     names_types_fields.extend(
    862         cls._flatten_schema(t_, name_prefix=inner_prefix)
    863     )
    864 elif issubclass(t_, AbstractTensor):

File <frozen abc>:123, in __subclasscheck__(cls, subclass)

TypeError: issubclass() arg 1 must be a class
```

This also happens in other typings like Sequence, Iterable and Tuple.

**Comment by JohannesMessner** [comment]
Hi @lazyhope, thanks for catching this.

The index should not break in this way, but it also doesn't make so much sense to use a DocIndex for vector search without having a vector field in your document.
But still, this user experience is not great, we should either allow this (despite it not making so much sense), or we should fail with an informative error message.

**Comment by lazyhope** [comment]
> Hi @lazyhope, thanks for catching this.
> 
> The index should not break in this way, but it also doesn't make so much sense to use a DocIndex for vector search without having a vector field in your document - I think that might be the root cause here.
> But still, this user experience is not great, we should either allow this (despite it not making so much sense), or we should fail with an informative error message.
> 
> Edit: Actually, maybe the lack of embedding vector might not be the issue, the use of `List` might be, in which case, yeah, that's a clear bug. @lazyhope does this still happen if you add a field of type `NdArray` or similar?

Yes, I was just giving a simple example. This still happens when I add two fields of type TorchTensor[768], so I think the problem was caused by the List[str] field.

**Comment by JohannesMessner** [comment]
Got it! Definitely a bug then. We'll have someone work on this most likely this week.

**Comment by JohannesMessner** [comment]
For reference to whoever will take this: It seems like in `BaseDocIndex._flatten_schema` we perform an instance or subclass check that assumes that the type of every field is a class - however this is not the case, `List[int]` for example is not a class, and thus `issubclass` will fail (thanks, Python).

I suspect that we have the same or similar issues in multiple places.
I suggest we switch to a custom implementation of `issubclass` and `isinstance` that can handle such things by simply returning `False` instead of failing.

To do that, let's:
- see if the `typing_inspect` offers such a thing
- if not, see if pydantic has this implemented for their internal use
- if not, build our own

and use it "everywhere" to avoid such things in other places

**Comment by maxwelljin** [comment]
I'll take this ticket. I'd investigated the issue further and fix the BaseDocIndex._flatten_schema function.
