### ISSUE TITLE
Support for nested lists in Docs - DocArray V2

### ISSUE THREAD

**Issue by dwlmt** [docarray/docarray#1577]
I want to use DocArray V2 0.32 to store nested objects where each object is a list and can have its embedding. The idea is to extract multilevel categories and key phrases from a longer text and store these in a sub-index in a Qdrant. But whenever I try and set it fails to convert when sending over gRPC. 

First, should DocArray support this kind of nesting or just flat sub-classes? Second, if it should support this, I'm not sure if it is a bug or if there is another way of doing this?

**The error:**

│ /opt/homebrew/lib/python3.11/site-packages/docarray/base_doc/mixins/io.py:312 in                 │
│ _get_content_from_node_proto                                                                     │
│                                                                                                  │
│   309 │   │   │   │   return_field = getattr(value, content_key)                                 │
│   310 │   │   │                                                                                  │
│   311 │   │   │   elif content_key in arg_to_container.keys():                                   │
│   312 │   │   │   │   field_type = cls.__fields__[field_name].type_ if field_name else None      │
│   313 │   │   │   │   return_field = arg_to_container[content_key](                              │
│   314 │   │   │   │   │   cls._get_content_from_node_proto(node, field_type=field_type)          │
│   315 │   │   │   │   │   for node in getattr(value, content_key).data  
KeyError: 'terms'

**Below is the basic setup:**

class TermDoc(BaseDoc):
    text: Optional[str]
    embedding: Optional[NdArray[dim_size]] = Field(space=similarity)
    
class CategoryDoc(BaseDoc):
    level: int
    text: str
    embedding: Optional[NdArray[dim_size]] = Field(space=similarity)

class ProductDoc(BaseDoc):
    sku: Optional[str]
    ...
    categories: Optional[List[CategoryDoc]]
    terms: Optional[List[TermDoc]]

**Comment by dwlmt** [comment]
It's okay I worked it out, the nested types have to be DocLists as in the Legacy Documents chunks. Would be nice to have an example of this in the Documentation.

categories: Optional[DocList[CategoryDoc]]
terms: Optional[DocList[TermDoc]]

**Comment by JoanFM** [comment]
Hey @dwlmt ,

Would it be possible for you to suggest an example and where it would be helpful to you and come with a PR to contribute?
