### ISSUE TITLE
Inquiry regarding DocArray support for chunks in version 0.30 or higher

### ISSUE THREAD

**Issue by xiaojinwhu** [docarray/docarray#1578]
I am currently utilizing DocArray version 0.30 for constructing a list-like data structure. However, I have encountered an issue with indexing. I would like to inquire about the support for chunks in versions 0.30 or higher of DocArray.

**Comment by xiaojinwhu** [comment]
as https://github.com/docarray/docarray/issues/1577

**Comment by xiaojinwhu** [comment]
<img width="902" alt="image" src="https://github.com/docarray/docarray/assets/10114923/4932f03c-d767-4a3d-842f-51412e395980">

as see above, 0.32.0 seems not support chunks as V1 before

**Comment by JoanFM** [comment]
Can you copy paste here the code to see what is going wrong?

**Comment by JoanFM** [comment]
OK, I can reproduce, will try to fix ASAP

**Comment by JoanFM** [comment]
Hello @xiaojinwhu ,

Can you check if this branch would fix the issue? 

https://github.com/docarray/docarray/pull/1582

And what is your expected behavior?

**Comment by JoanFM** [comment]
Do you expect `subindex` to work in this case?

**Comment by xiaojinwhu** [comment]
> 

Thanks, It worked

**Comment by xiaojinwhu** [comment]
> Do you expect `subindex` to work in this case?

Indeed, I need to use subindex. It seems like I should opt for a different indexing approach.

**Comment by xiaojinwhu** [comment]
> Do you expect `subindex` to work in this case?

I am using HnswDocumentIndex, but I can't find a way to use subindex for searching. The methods 'find' and 'find_subindex' don't work on the terms (Doclist) (an instance has multiple synonym vectors). The subindexes in the documents are not similar to the chunks in version V1. How can I implement this?

**Comment by JoanFM** [comment]
What exact code are you running, can you paste it here so that we can check?

Chunks in v1 are similar to nested DocLists in this new version, I am not sure why you consider it not to be.

**Comment by xiaojinwhu** [comment]
> What exact code are you running, can you paste it here so that we can check?
> 
> Chunks in v1 are similar to nested DocLists in this new version, I am not sure why you consider it not to be.

<img width="846" alt="image" src="https://github.com/docarray/docarray/assets/10114923/bc3f2d9e-e578-4a54-b90e-de9da6654b80">

As shown in the figure above, it demonstrates the business logic implemented in version V1. 
The core is to search the chunks (subindex) in V1, and then return its root. 
Now, I am trying to implement it using V2, but I haven't found a way, because the nested indexes in the instance are all nested with a class (BaseDoc) instead of (DocList).

Thanks

**Comment by JoanFM** [comment]
Have you checked the documentation here?

https://docs.docarray.org/user_guide/storing/docindex/

at the end of the page, it is explained how nested search with subindex work

**Comment by xiaojinwhu** [comment]
Thank you very much. 
According to the documentation, it's now running successfully. I wasn't reading the documentation in detail before.
