### ISSUE TITLE
Field of type `List[str]` is shown as `str` in the output of `DocList.summary`

### ISSUE THREAD

**Issue by lazyhope** [docarray/docarray#1592]
When defining a field's type using `List[str]`:
```python
class TestDoc(BaseDoc):
    str_list: List[str]

dl = DocList[TestDoc]([TestDoc(str_list=[]), TestDoc(str_list=["1"])])
dl.summary()
```
Output:
```
╭─────── DocList Summary ───────╮
│                               │
│   Type     DocList[TestDoc]   │
│   Length   2                  │
│                               │
╰───────────────────────────────╯
╭─── Document Schema ───╮
│                       │
│   TestDoc             │
│   └── str_list: str   │
│                       │
╰───────────────────────╯
```
The type of `str_list` being `str` is wrong.

**Comment by lazyhope** [comment]
I suppose the issue comes from this line: https://github.com/docarray/docarray/blob/f765d9f4f01089d0ab361cecd771efc97970ce92/docarray/display/document_summary.py#L65.

And this stackoverflow post may help:
https://stackoverflow.com/questions/75165745/cannot-determine-if-type-of-field-in-a-pydantic-model-is-of-type-list

Maybe consider using or combining `value.annotation` to determine the `field_type`?

**Comment by samsja** [comment]
So it looks like this is only a display issue right ? 

Indeed the line you pointed at is problematic. We will take a look and fix it

**Comment by lazyhope** [comment]
> So it looks like this is only a display issue right ?
> 
> Indeed the line you pointed at is problematic. We will take a look and fix it

I am not sure if it is a display issue only, any class that uses this `schema_summary` could be affected.
