### ISSUE TITLE
Question: How to change `RuntimeConfig`.

### ISSUE THREAD

**Issue by JoanFM** [docarray/docarray#1608]
It is not clear in Documentation how `RuntimeConfig` should be used and configured in Indexes.

It seems there is a `db.configure` method which allows it to change, but there is something weird. The runtime configuration is applied at `__init__` time which makes any `configure` call not applicable. 

This happens at least for `HnswLib`

**Comment by JohannesMessner** [comment]
`.configure()` should apply the changes. If it doesn't it is a bug. Could you share some code to reproduce?
