### ISSUE TITLE
Add a method to check if a document is already index

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1629]
# Context

We should add a method in `BaseDocIndex` to check if a document is already indexed in the database.
In short what it would do is to check the `id` of the given document and check if it already exist in the database.

**Comment by maxwelljin** [comment]
Also, should we consider support for nested documents when checking if a document has already been indexed? In other words, should we provide a feature that allows users to check whether a sub-document (within the context of a nested document) is stored in the indexer?

**Comment by JoanFM** [comment]
lets do one feature a time

**Comment by samsja** [comment]
> Also, should we consider support for nested documents when checking if a document has already been indexed? In other words, should we provide a feature that allows users to check whether a sub-document (within the context of a nested document) is stored in the indexer?

this could makes sense, lets try to do it once we merge the first PR
