### ISSUE TITLE
Bug: Equality of DocVec

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1638]
Equality between instances of DocVec does not seem to work properly:

```python
from docarray import BaseDoc, DocList


class CustomDocument(BaseDoc):
    image: str


da = DocList[CustomDocument](
    [CustomDocument(image='hi') for _ in range(10)]
).to_doc_vec()

da2 = DocList[CustomDocument](
    [CustomDocument(image='hi') for _ in range(10)]
).to_doc_vec()

print(da == da2)
```
```bash
False
```

**Comment by npitsillos** [comment]
I can take this @JohannesMessner. Should this follow the same implementation as `DocList.__eq__()`?

**Comment by JohannesMessner** [comment]
> I can take this @JohannesMessner. Should this follow the same implementation as `DocList.__eq__()`?

Honestly I haven't checked that, but it is probably a good place to get inspiration from

**Comment by samsja** [comment]
I think we should rather check that the columns in the storage are equal

**Comment by JohannesMessner** [comment]
> Could you be more specific @samsja?

i think for two DocVecs to be considered equal, the following must hold:
- their `doc_type` is equal
- their `tensor_type` is equal
- their `_storage` is equal

In turn, the `ColumnStorage` should be equal in tensor_columns, doc_columns, docs_vec_columns, any_columns, and tensor_type

**Comment by npitsillos** [comment]
In checking the `ColumnStorage` I see that when using the example provided above `tensor_columns`, `doc_columns` and `doc_vec_columns` are empty and that `any_columns` contains an `id` and `image` key. I am assuming the `id` key will exist for all the above attributes. I should ignore the value of `id` and skip to the rest of the keys in every `dict` when checking for equality?

**Comment by JohannesMessner** [comment]
> I should ignore the value of id and skip to the rest of the keys in every dict when checking for equality?

Let's handle the `.id` the same way equality on `BaseDoc` handles it. Off the top of my head I am not sure what it does, consider the id or ignore it.

**Comment by npitsillos** [comment]
`BaseDoc` ignores the `id` values https://github.com/docarray/docarray/blob/eedd83ce249941493a23bc32fc862ba7353d732c/docarray/base_doc/doc.py#L173-L174
