### ISSUE TITLE
Weaviate storage doesn't support basic authentication

### ISSUE THREAD

**Issue by girishc13** [docarray/docarray#1671]
### Initial Checks

- [X] I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug

### Description

Weviate [v3.9.0](https://github.com/weaviate/weaviate-python-client/releases/tag/v3.9.0) supports the `additional_headers` dict for passing in basic authentication key. WeviateConfig in docarray doesn't list this header value and prevents me from authenticating against a cluster with authentication enabled.

### Python, Pydantic & OS Version

```Text
0.21.0
```

**Comment by JoanFM** [comment]
Fixed in release v0.21.1
