### ISSUE TITLE
`tensor_type` argument for all DocVec deserializations

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1677]
`DocVec.from_protobuf(tensor_type=...)` already exists, but this needs to be the case for all deserializations:
- proto
- json
- pandas
- bytes
- binary
- base64

Otherwise there is no way of knowing if the deserialized DocVec should use torch, np, or tf

**Comment by JoanFM** [comment]
Can you elaborate more? does it need to be added, removed, commented?

**Comment by JohannesMessner** [comment]
@JoanFM you need to slow down a bit, you're faster at commenting than I am at filling in the description of my own issue ;)

**Comment by JoanFM** [comment]
haha sorry, I just happened to be watching at that time
