### ISSUE TITLE
can not storage new chunk to the sqlite

### ISSUE THREAD

**Issue by xiyuanba** [docarray/docarray#1702]
### Initial Checks

- [X] I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug

### Description

I tried to append a chunk to a document, but when I synchronized it to sqlite, I felt that the synchronization action did not take effect. I kept overwriting the second chunk, but there was no actual append action

may be the problem in the code below

```python
for d in self._da:
    if d.text == doc.text:
        print(f'{doc.text} already exists in the index')
        d.chunks.append(Document(uri=doc.uri, text=doc.text, embedding=features))
        print(f'adding {doc.text} to the chunk of {d.text}')
        print(f'length of chunks:', len(d.chunks))
        d.summary()
    self._da.sync()

    return docs
```
### Example Code

```Python
class FaceEmbeddingExecutor(Executor):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.model = InceptionResnetV1(pretrained='vggface2').eval()
        self._da = DocumentArray(
            storage='sqlite', config={'connection': 'example.db', 'table_name': 'face'}
        )

    @requests
    def encode(self, docs: DocumentArray, *args, **kwargs):
        # 创建一个 Document 对象并设置其属性值
        for doc in docs:
            print(doc.text)
            image = cv2.imread(doc.uri)
            # 使用 face_recognition 库检测人脸
            face_locations = face_recognition.face_locations(image)
            # 遍历检测到的人脸区域
            for i, face_location in enumerate(face_locations):
                top, right, bottom, left = face_location
                # 截取人脸区域
                face_image = image[top:bottom, left:right]

                # 调整人脸区域大小为 160x160
                resized_image = cv2.resize(face_image, (160, 160))

                # 保存新图像到临时文件
                with tempfile.NamedTemporaryFile(suffix='.jpg', delete=False) as temp_file:
                    temp_filename = temp_file.name
                    cv2.imwrite(temp_filename, resized_image)

                # 从临时文件中读取图像并进行保存
                saved_image = cv2.imread(temp_filename)
                filename = f'index_tmp{i + 1}.jpg'
                cv2.imwrite(filename, saved_image)
                tmp_img = cv2.imread(filename)
                tmp_img = cv2.cvtColor(tmp_img, cv2.COLOR_BGR2RGB)
                tmp_img = (tmp_img / 255.).astype(np.float32)
                with torch.no_grad():
                    features = self.model(torch.from_numpy(np.array([tmp_img.transpose(2, 0, 1)])))
                features = features.detach().numpy()
                for d in self._da:
                    if d.text == doc.text:
                        print(f'{doc.text} already exists in the index')
                        d.chunks.append(Document(uri=doc.uri, text=doc.text, embedding=features))
                        print(f'adding {doc.text} to the chunk of {d.text}')
                        print(f'length of chunks:', len(d.chunks))
                        d.summary()
                    self._da.sync()

                    return docs

                da_doc = Document(text=doc.text)
                da_doc.chunks.append(Document(uri=doc.uri, text=doc.text, embedding=features))
                print(f'adding {doc.text} to the index')
                da_doc.summary()
                self._da.append(da_doc)
                self._da.sync()

            return docs
```

### Python, Pydantic & OS Version

```Text
0.21.1
```

**Comment by JoanFM** [comment]
It is not clear, why do u consider it not to be working. 

Can you show a simpler script to reproduce the issue? With the expected and the obtained behavior?

**Comment by xiyuanba** [comment]
My expectation is to add a new chunk to a document and synchronize it to sqlite like this

└── document
    ├── chunk1
    ├── chunk2
    └── chunk3
My expectation is to add a new chunk to a document and synchronize it to sqlite. I anticipate that d. chunks. append (Document (uri=doc. uri, text=doc. text, embedding=features) will work, but it doesn't. What do I need to do to finally synchronize the newly added chunk to sqlite?


> It is not clear what u are trying to do
> 
> But:
> 
> ```python
> for d in self._da:
>     if d.text == doc.text:
>         print(f'{doc.text} already exists in the index')
>         d.chunks.append(Document(uri=doc.uri, text=doc.text, embedding=features))
>         print(f'adding {doc.text} to the chunk of {d.text}')
>         print(f'length of chunks:', len(d.chunks))
>         d.summary()
>     self._da.sync()
> 
>     return docs
> ```
> 
> This is not expected to add the chunks in the SQLite database. If u want to updatre what is inside the database, u need to get it from the database, change it and update that Document explicitly.

My expectation is to add a new chunk to a document and synchronize it to sqlite like this

└── document
    ├── chunk1
    ├── chunk2
    └── chunk3
My expectation is to add a new chunk to a document and synchronize it to sqlite. I anticipate that d. chunks. append (Document (uri=doc. uri, text=doc. text, embedding=features) will work, but it doesn't. What do I need to do to finally synchronize the newly added chunk to sqlite?

**Comment by xiyuanba** [comment]
> It is not clear what u are trying to do
> 
> But:
> 
> ```python
> for d in self._da:
>     if d.text == doc.text:
>         print(f'{doc.text} already exists in the index')
>         d.chunks.append(Document(uri=doc.uri, text=doc.text, embedding=features))
>         print(f'adding {doc.text} to the chunk of {d.text}')
>         print(f'length of chunks:', len(d.chunks))
>         d.summary()
>     self._da.sync()
> 
>     return docs
> ```
> 
> This is not expected to add the chunks in the SQLite database. If u want to updatre what is inside the database, u need to get it from the database, change it and update that Document explicitly.

My expectation is to add a new chunk to a document and synchronize it to sqlite like this

└── document
    ├── chunk1
    ├── chunk2
    └── chunk3
My expectation is to add a new chunk to a document and synchronize it to sqlite. I anticipate that d. chunks. append (Document (uri=doc. uri, text=doc. text, embedding=features) will work, but it doesn't. What do I need to do to finally synchronize the newly added chunk to sqlite?

**Comment by JoanFM** [comment]
I believe u can do something like:

```self._da[doc.id] = doc```

This will reinject the Documentation into the SQLIte database I believe

**Comment by xiyuanba** [comment]
> I believe u can do something like:
> 
> `self._da[doc.id] = doc`
> 
> This will reinject the Documentation into the SQLIte database I believe

thanks,it's worked
