### ISSUE TITLE
TorchTensor cannot be deep copied.

### ISSUE THREAD

**Issue by gusseppe** [docarray/docarray#1719]
Describe the bug
TorchTensor cannot be deep copied.

docarray.__version__
'0.36.0'

Related:
#1143 

To Reproduce
script.py

```python 
import torch
from docarray import BaseDoc
from docarray.typing import TorchTensor
class Meow(BaseDoc):
    embedding : TorchTensor

a = Meow(embedding=torch.randn(42))
print(id(a.embedding), id(a.copy(deep=True).embedding))
```

_Originally posted by @gusseppe in https://github.com/docarray/docarray/issues/1131#issuecomment-1644616321_

**Comment by JoanFM** [comment]
Hey @gusseppe,

What is the exact error u see?

**Comment by gusseppe** [comment]
Apologize for the late response, but the error is similar to the related bug #1131:

`RuntimeError: The default implementation of __deepcopy__() for non-wrapper subclasses only works for subclass types that implement new_empty() and for which that function returns another instance of the same subclass. You should either properly implement new_empty() for your subclass or override __deepcopy__() if it is intended behavior for new_empty() to return an instance of a different type.`

**Comment by JoanFM** [comment]
We have seen it, the fix has been merged and will be released soon

**Comment by gusseppe** [comment]
Super great! thanks!

**Comment by JoanFM** [comment]
You can enjoy thr fix by installing the prerelease `pip install docarray --pre`
