### ISSUE TITLE
0.36 Nested Collections not stored in a separate Sub Index

### ISSUE THREAD

**Issue by dwlmt** [docarray/docarray#1721]
### Initial Checks

- [X] I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug

### Description

I have a document structure as per the docs given below. Until version 0.36, the nested fields "paths" were stored in separate collections with Qdrant. So with a collection name of "channel_category" for the parent doc, the paths would be stored in "channel_category__paths". With 0.36 the nested paths vectors and their collections are being held in the parent collection "channel_category" as separate records. Is this an intended change or a bug in how nested data is stored?
```python

class MetaPathDoc(BaseDoc):
    path_id: str
    level: int
    text: str
    embedding: Optional[AnyTensor] = Field(
        space=similarity_space, dim=dim_size)

class MetaCategoryDoc(BaseDoc):
    node_id: Optional[str]
    node_name: Optional[str]
    name: Optional[str]
    product_type_definitions: Optional[str]
    leaf: bool
    paths: Optional[DocList[MetaPathDoc]]
    embedding: Optional[AnyTensor] = Field(
        space=similarity_space, dim=dim_size)
    channel: str
    lang: str
```

### Example Code

I'm loading documents to QDrant via a Jina executor like this:
```python
import os
import sys

import more_itertools
from docarray import DocList
from docarray.index import QdrantDocumentIndex
from utils.docs import MetaCategoryDoc
from jina import Executor, requests
from jina.logging.logger import JinaLogger
from qdrant_client.http import models

QDRANT_LOCATION = os.getenv('QDRANT_LOCATION', "http://localhost:6333")
QDRANT_API_KEY = os.getenv('QDRANT_API_KEY', None)

class MetaChannelCategoryIndexingExec(Executor):
    def __init__(self,
                 collection_name: str = "channel_category",
                 batch_size: str = 64,
                 qdrant_location: str = QDRANT_LOCATION,
                 qdrant_api_key: str = QDRANT_API_KEY,
                 *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.logger = JinaLogger('meta_channel_category_indexing')


        db_config = QdrantDocumentIndex.DBConfig(
            location=qdrant_location,
            api_key=qdrant_api_key,
            collection_name=collection_name,
            quantization_config=models.ScalarQuantization(
                scalar=models.ScalarQuantizationConfig(
                    type=models.ScalarType.INT8,
                    quantile=0.99,
                    always_ram=False,
                )
            ),
            optimizers_config=models.OptimizersConfigDiff(
                memmap_threshold=20000, indexing_threshold=20000),
            on_disk_payload=True,
            hnsw_config=models.HnswConfigDiff(m=16,ef_construct=100,on_disk=True),
            wal_config=models.WalConfigDiff(
                wal_capacity_mb=64, wal_segments_ahead=1),
            prefer_grpc=False)

        self.doc_index = QdrantDocumentIndex[MetaCategoryDoc](db_config)
        self.batch_size = batch_size

    @requests(
        request_schema=DocList[MetaCategoryDoc],
        response_schema=DocList[MetaCategoryDoc]
    )
    def index_metadata(self, docs, **kwargs):
        """ Save products to the Vector DB.
        """
        for doc_batch in more_itertools.chunked(docs, self.batch_size):
            # Indexing the documents
            self.doc_index.index(
                doc_batch
            )
```

### Python, Pydantic & OS Version

```Text
0.36.0
```

### Affected Components

- [X] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [X] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [ ] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [ ] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [ ] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

**Comment by dwlmt** [comment]
Another issue is I have structures like the following. These contain multiple embeddings at the top level and also TermDoc has embeddings for each item in the list. It seems as if now it only works with multiple embeddings at the parent doc, or a single embedding with the parent and the nested embeddings but not both. It will give an error from QDrant saying "title_embedding" does not exist which I assume is because this isn't in the TermDoc in the same collection.

class ProductDoc(ProductCoreDoc):
    ...
    terms: Optional[DocList[TermDoc]]
    title_embedding: Optional[AnyTensor] = Field(
        space=similarity_space, dim=dim_size)
    description_embedding: Optional[AnyTensor] = Field(
        space=similarity_space, dim=dim_size)
    category_embedding: Optional[AnyTensor] = Field(
        space=similarity_space, dim=dim_size)
    embedding: Optional[AnyTensor] = Field(
        space=similarity_space, dim=dim_size)

**Comment by JoanFM** [comment]
First of all,

Can you confirm that it did not work the same in 0.35.0?

**Comment by dwlmt** [comment]
Yes, if I downgrade to 0.35.0 I get this from Qdrant where the paths is created as a separate collection:

collections=[CollectionDescription(name='channel_category_nested'), ... CollectionDescription(name='channel_category_nested__paths')]

**Comment by JoanFM** [comment]
@kacperlukawski may be able to help here and give better insights.

**Comment by JoanFM** [comment]
I believe this issue is caused by #1705

**Comment by dwlmt** [comment]
@JoanFM thanks for this. I see a fix has been merged to main. I assume this will be in the next 0.37.0 release.

**Comment by JoanFM** [comment]
yes, u can also have it if u use the prerelease by `pip install docarray --pre`
