### ISSUE TITLE
Add Field Description and example to Predefined Documents

### ISSUE THREAD

**Issue by JoanFM** [docarray/docarray#1736]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.docarray.org) and still think this feature is missing

### Description

One nice thing about DocArray is the predefined Document types that we offer that allow people to use for multimodal applications.

Having rich field definitions, with description and examples would help when building services based on FastAPI with them.

### Affected Components

- [ ] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [X] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [X] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [ ] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [X] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

**Comment by punndcoder28** [comment]
Hi, @JoanFM I can take this up and work on the changes. Could you provide more information on what is required for the change? Happy to work on it

**Comment by JoanFM** [comment]
Hello @punndcoder28,

Sure, what u need is to slowly add meaningful descriptions, use `Field(description=...)` to the fields of the predefined documents. You can split it in multiple PR

**Comment by punndcoder28** [comment]
Thanks for the quick reply. The predefined document types are those of `TextDoc`, and `ImageDoc` and the list of other docs and field descriptions, for example on `TextDoc`, would be concise information for attributes `text`, `url`, `embeddings` and `bytes`?

**Comment by JoanFM** [comment]
yes, you can add description and example field

**Comment by punndcoder28** [comment]
The `description` field would be for the document type and the example would be a separate section in the docs page?

**Comment by JoanFM** [comment]
It is not about docs page sections, is about completing the fields of the predefined documents as it has been done for `ID` for the abstract `BaseDoc` https://github.com/docarray/docarray/blob/cc2339db44626e622f3b2f354d0c5f8d8a0b20ea/docarray/base_doc/doc.py#L75

**Comment by punndcoder28** [comment]
Thank you for the clarification

**Comment by punndcoder28** [comment]
@JoanFM I seem to have added field descriptions for all the predefined documents (which were present on docs). Are there any more I've missed?
