### ISSUE TITLE
Crash when using non-class type field in Document with QdrantDocumentIndex

### ISSUE THREAD

**Issue by TerboucheHacene** [docarray/docarray#1748]
### Initial Checks

- [X] I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug

### Description

I'm encountering an issue when attempting to define an index of type QdrantDocumentIndex for documents that include fields with non-class types (e.g., lists). The error message I'm receiving is as follows:
```
TypeError: issubclass() arg 1 must be a class
```
It seems that this error is related to the interaction between the document's fields and the index definition. The error happens in: https://github.com/docarray/docarray/blob/adb0d0141032c72cf2412a8b998c78cd9a920a9e/docarray/index/backends/qdrant.py#L272

I suggest the following:
`if any(safe_issubclass(python_type, vt) for vt in QDRANT_PY_VECTOR_TYPES):`

Steps to Reproduce:

1. Create a Document with a field of non-class type (e.g., a list).
2. Attempt to define an index of type QdrantDocumentIndex for the created Document.
3. Observe the TypeError mentioned above.

### Example Code

```Python
from docarray import DocVec, BaseDoc
from docarray.index import QdrantDocumentIndex

class DocPaper(BaseDoc):
    id: str
    title: str
    abstract: str
    authors: List[str]

host = "localhost"
port = 6333
collection_name = "papers"
qdrant_config = QdrantDocumentIndex.DBConfig(
    host=host, port=port, collection_name=collection_name
)
doc_index = QdrantDocumentIndex[DocPaper](qdrant_config)
```

### Python, Pydantic & OS Version

```Text
0.37.0, ubuntu system, Python 3.9.16
```

### Affected Components

- [X] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [ ] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [ ] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [ ] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [ ] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

**Comment by JoanFM** [comment]
Hey @TerboucheHacene,

Your suggestion would be correct, could you open a PR and add a test case with this fix?

That would be awesome
