### ISSUE TITLE
_pickle.PicklingError encountered when attempting to serialize `BaseDoc` type

### ISSUE THREAD

**Issue by beidongjiedeguang** [docarray/docarray#1760]
### Initial Checks

- [X] I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug

### Description

After using `docarray.documents.helper.create_doc` to create a `BaseDoc` type, this type cannot be serialized by Pickle:

```python
from docarray.documents.helper import create_doc

MyDoc = create_doc(
        'MyDoc',
        title=(str, ...),
        title_tensor= (Optional[NdArray[128]], ...),
        )

buffer = pickle.dumps(MyDoc)
```

Out:
```bash
_pickle.PicklingError: Can't pickle <class 'docarray.documents.helper.MyDoc'>: attribute lookup MyDoc on docarray.documents.helper failed
```

### Python, Pydantic & OS Version

```Text
docarray: 0.37.1  
python: 3.10.12
```

### Affected Components

- [ ] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [ ] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [ ] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [ ] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [ ] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

**Comment by beidongjiedeguang** [comment]
Hi @JoanFM ,
Yes, because this type is dynamically created. If it is not saved, it will need to be recreated the next time  `DocIndex`(such as [HnswDocumentIndex](https://docs.docarray.org/user_guide/storing/index_hnswlib/)) is launched. Therefore, I must save the metadata for creating this class. So if possible, I would like to directly save this type.

**Comment by JoanFM** [comment]
So, a solution is to declare it with module parameter:

```python
from docarray.documents.helper import create_doc
import pickle


MyDoc = create_doc(
    'MyDoc',
    __module__=__name__,
    title=(str, ...)
)

buffer = pickle.dumps(MyDoc)
```
This works for me
