### ISSUE TITLE
Inconsistent `to_json()` return type

### ISSUE THREAD

**Issue by deepankarm** [docarray/docarray#1766]
### Initial Checks

- [X] I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug

### Description

`to_json()` returns a `str` for models inherited from `BaseDoc`, whereas it is `bytes` for `DocList`

### Example Code

```Python
from docarray import BaseDoc, DocList


class MyModel(BaseDoc):
    text: str
        
print(type(MyModel(text="abc").to_json())) # <class 'str'>
print(type(DocList[MyModel]([MyModel(text="abc")]).to_json())) # <class 'bytes'>
```

### Docarray Version

```Text
0.37.1
```

### Affected Components

- [ ] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [ ] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [X] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [ ] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [ ] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

**Comment by JohannesMessner** [comment]
I will take a look
