### ISSUE TITLE
Request for support for MongoDB Atlas Vector Search as DocIndex

### ISSUE THREAD

**Issue by matbmeijer** [docarray/docarray#1768]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.docarray.org) and still think this feature is missing

### Description

Similar to another `DocIndex` such as ElasticSearch v8, I would kindly request the feature to support MongoDB Atlas Vector Search and create a `DocIndex` class for it. I would be happy to contribute to this feature.

Documentation about it can be found here:
- How to index: https://www.mongodb.com/docs/atlas/atlas-search/field-types/knn-vector/
- Search: https://www.mongodb.com/docs/atlas/atlas-search/knn-beta/
- Demo: https://github.com/afsungur/mongodb-atlas-vector-search-fashion-products

### Affected Components

- [X] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [ ] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [ ] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [ ] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [ ] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

**Comment by JoanFM** [comment]
Hello @matbmeijer ,

We would be really happy to have this feature. However, we do not have currently the capacity to provide this, but we would be happy to help in this contribution.

**Comment by JoanFM** [comment]
Hello @matbmeijer ,

Is there any chance that you can get to work on this? How can we help?

**Comment by JoanFM** [comment]
Hello @matbmeijer ,

Any news about this request? Is this still something you would consider to provide?

**Comment by matbmeijer** [comment]
Hi @JoanFM, we just activated the vector database feature within MongoDB in our company. Although I do not have any kind of timeline, I hope to be able to evaluate the complexity of developing the support for `docarray`. I would be more than happy to collaborate with others.

**Comment by JoanFM** [comment]
Hey @matbmeijer ,

If you join our discord, we should be able to help you together with the rest of the community.

**Comment by blink1073** [comment]
This was fixed by https://github.com/docarray/docarray/pull/1883 :tada:
