### ISSUE TITLE
Bug with DocList[]

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1782]
# Context
```python
from docarray import DocList, BaseDoc

docs = DocList[BaseDoc()]# 1

class MyDoc(BaseDoc):
    text: str

DocList[MyDoc][MyDoc] # 2
```

Both 1 and 2 lines should failed with a nice error message

## description

DocList[X] should only accept BaseDoc class and should not be called twice

## How to do it

This should be as easy as adding if else statement and raise properly error in this part of the codebase:

https://github.com/docarray/docarray/blob/715252a72177e83cb81736106f34d0ab2960ce56/docarray/array/any_array.py#L56

**Comment by punndcoder28** [comment]
Hi @samsja I can work on this. From the docs I understand that the correct way is
```
from docarray import DocList, BaseDoc

class MyDoc(BaseDoc):
    text: str

docs = DocList[BaseDoc]([MyDoc])
```

**Comment by punndcoder28** [comment]
Understood. Will go through the custom implementation of `safe_issubclass` method and propose a solution for this issue

**Comment by JoanFM** [comment]
I do not think is that code u have to check, is the specific line, the `safe_issubclass` method should not be touched I think

**Comment by punndcoder28** [comment]
Not related to this issue but how do I test out my changes by locally building the library and importing it in a local python script

**Comment by punndcoder28** [comment]
Checked the implementation of classes `DocList` and `AnyDocArray` and noticed that https://github.com/docarray/docarray/blob/d0b99909052d1640670764015e4e385319fdc776/docarray/array/doc_list/doc_list.py#L338
the above line fails when we do
```
from docarray import DocList, BaseDoc

doc = DocList[BaseDoc()]
```
and the control goes to
https://github.com/docarray/docarray/blob/d0b99909052d1640670764015e4e385319fdc776/docarray/array/doc_list/doc_list.py#L341
but does not end up in the class `AnyDocArray` so we can handle this case in `__class_getitem__` method of `DocList` by adding a condition to check
`if isinstance(item, object)` and raise an exception of type `ValueError`

**Comment by JoanFM** [comment]
> Checked the implementation of classes `DocList` and `AnyDocArray` and noticed that
> 
> https://github.com/docarray/docarray/blob/d0b99909052d1640670764015e4e385319fdc776/docarray/array/doc_list/doc_list.py#L338
> 
> 
> the above line fails when we do
> ```
> from docarray import DocList, BaseDoc
> 
> doc = DocList[BaseDoc()]
> ```
> 
> and the control goes to
> 
> https://github.com/docarray/docarray/blob/d0b99909052d1640670764015e4e385319fdc776/docarray/array/doc_list/doc_list.py#L341
> 
> 
> but does not end up in the class `AnyDocArray` so we can handle this case in `__class_getitem__` method of `DocList` by adding a condition to check
> `if isinstance(item, object)` and raise an exception of type `ValueError`

sounds reasonable

**Comment by JoanFM** [comment]
The second part of the ticket remains valid, will open a new issue
