### ISSUE TITLE
[pydantic 2] create pydantic model from schema

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1786]
# Context

creating pydantic model from schema is not working bc pydantic v2 does not expose anymore the right method

https://github.com/docarray/docarray/blob/4ef493943d1ee73613b51800980239a30fe5ae73/tests/units/util/test_create_dynamic_code_class.py#L17

https://github.com/docarray/docarray/blob/4ef493943d1ee73613b51800980239a30fe5ae73/docarray/utils/create_dynamic_doc_class.py#L54

**Comment by JoanFM** [comment]
Any clue why this is not doable in Pydantic V2?
