### ISSUE TITLE
[pydantic v2] create_doc_from_typeddict is not working

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1788]
# context

the `create_doc_from_typeddict` is not wokring with pydantic v2 because `create_model_from_typeddict` does not exist in pydantic v2

https://github.com/docarray/docarray/blob/4ef493943d1ee73613b51800980239a30fe5ae73/tests/integrations/document/test_document.py#L87

https://github.com/docarray/docarray/blob/4ef493943d1ee73613b51800980239a30fe5ae73/docarray/documents/helper.py#L11

**Comment by JoanFM** [comment]
I think this method is deprecated, therefore the actual behavior is correct, just raise an Exception
