### ISSUE TITLE
TorchTensor deepcopy raises error when dtype is not float32

### ISSUE THREAD

**Issue by igamenovoer** [docarray/docarray#1831]
### Initial Checks

- [X] I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug

### Description

when calling copy.deepcopy() over TorchTensor, it fails when tensor.dtype != torch.float32.
The problem is that TorchTensor.new_empty() will create a float32 tensor no matter what, regardless of self.dtype
![image](https://github.com/docarray/docarray/assets/9019398/084bf488-827b-4466-a724-da95790b3ad0)

### Example Code

```Python
import torch
from docarray.typing.tensor.torch_tensor import TorchTensor
import copy

x = TorchTensor(torch.randn(2,3))
y = copy.deepcopy(x)    # this works

xx = TorchTensor(torch.randint(0,100,(2,3)))
yy = copy.deepcopy(xx)  # RuntimeError: Expected a Storage of type float or an UntypedStorage, but got type Long for argument 1 'storage'
```

### Python, DocArray & OS Version

```Text
0.39.1
```

### Affected Components

- [ ] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [X] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [ ] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [X] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [ ] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

**Comment by JoanFM** [comment]
Hey @igamenovoer,

Thanms for reporting the issue. Since you spotted the problem, would you like to contribute the fix?

**Comment by ai-naymul** [comment]
I think we need to add a custom implementation of `deepcopy `for TorchTensor to avoid storage-sharing issues.

@JoanFM could you please help me to contribute in this

**Comment by JoanFM** [comment]
what do u mean by a deepcopy class for that?

**Comment by ai-naymul** [comment]
> what do u mean by a deepcopy class for that?

Oh I am sorry I was mentioning method, It's was a typing mistake.

**Comment by JoanFM** [comment]
the approach seems to make sense indeed

**Comment by JoanFM** [comment]
yws

**Comment by ai-naymul** [comment]
> yws

@JoanFM would you mind having a look at the PR, please?
