### ISSUE TITLE
Support Epsilla as a document store

### ISSUE THREAD

**Issue by tonyyanga** [docarray/docarray#1832]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.docarray.org) and still think this feature is missing

### Description

Docarray supports a number of vector databases. [Epsilla](https://github.com/epsilla-cloud/vectordb) is an open source vector db with a cloud offering, but not currently supported.

I see a [past issue](https://github.com/docarray/docarray/issues/1245) with @JohannesMessner and @JoanFM that indicates docarray is open to supporting any kind of vector db, as long as the requester can contribute this feature. Is this still the case?

I am open to contributing this feature via PRs and will follow the contributing guideline.

### Affected Components

- [X] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [ ] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [ ] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [ ] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [ ] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

**Comment by JoanFM** [comment]
Hey @tonyyanga,

Sure you are more than welcome to contribute this feature. We would really appreciate it.

**Comment by tonyyanga** [comment]
Thanks! First PR with the code contributions is in: https://github.com/docarray/docarray/pull/1835

I plan to make a second PR to update the docs.

**Comment by tonyyanga** [comment]
Documentation PR: https://github.com/docarray/docarray/pull/1838

Thank you for the review.
