### ISSUE TITLE
Error type hints in Python3.12 (#1147)

### ISSUE THREAD

**Issue by 954-Ivory** [docarray/docarray#1839]
### Initial Checks

- [X] I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug

### Description

I encountered the following issue when using langchain in Python 3.12:

https://github.com/langchain-ai/langchain/issues/15016

```console
    return Generic.__class_getitem__.__func__(cls, item)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute '__func__'. Did you mean: '__doc__'?
```

It caused by this PR (https://github.com/docarray/docarray/pull/1147)

I think it can be changed like this:
```python
    def __class_getitem__(cls, item: Union[Type[BaseDocument], TypeVar, str]):
        if not isinstance(item, type):
            try:
                return Generic.__class_getitem__.__func__(cls, item)  # type: ignore
                # this do nothing that checking that item is valid type var or str
                # Keep the approach in #1147 to be compatible with lower versions of Python.
            except AttributeError:
                from types import GenericAlias
                return GenericAlias(cls, item)  # type: ignore
```

I want to know others' opinions.

### Example Code

```Python
https://learn.deeplearning.ai/langchain/lesson/5/question-and-answer
```

### Python, DocArray & OS Version

```Text
OS==Windows 22H2
Python==3.12.0
docarray==0.39.1
```

### Affected Components

- [X] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [ ] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [ ] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [ ] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [ ] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

**Comment by JoanFM** [comment]
hey @954-Ivory , would you be able to do a PR with the fix?

**Comment by 954-Ivory** [comment]
> hey @954-Ivory , would you be able to do a PR with the fix?

Yes, completed.
