### ISSUE TITLE
[Docs Missing] docs.docarray.org -> There isn't a GitHub Pages site here.

### ISSUE THREAD

**Issue by sudoskys** [docarray/docarray#1843]
### Initial Checks

- [ ] I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug

### Description

When i try to read docs, i got 404 pages

### Python, DocArray & OS Version

```Text
FireFox
```

### Affected Components

- [X] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [X] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [X] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [X] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [X] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

![Screenshot_20231223_153733](https://github.com/docarray/docarray/assets/75739606/c37dc889-f7e5-4630-9ceb-78434e758f1a)

**Comment by hanxiao** [comment]
fixed
