### ISSUE TITLE
customize load_uri related methods

### ISSUE THREAD

**Issue by DeoLeung** [docarray/docarray#289]
Hi, I have a question about the `load_uri_xxxx` methods

does it support customization?

supposed I have my images stored in to service where need to retrieve with authentication(compute some signature)

**Comment by hanxiao** [comment]
After communication, we found the user requires OSS support such as https://www.alibabacloud.com/product/object-storage-service

I suggest the team gives a review of the mainstream OSS providers and add a PR to improve this part

https://github.com/jina-ai/docarray/blob/73cb1f9b4e2550acd2bcababdc3531d440994e37/docarray/document/mixins/helper.py#L16-L19

Probably need help from our Chinese colleague @nomagick @numb3r3

**Comment by numb3r3** [comment]
This tool https://github.com/RaRe-Technologies/smart_open could be an easy solution. However, it only supports S3, GCS, Azure.

**Comment by nomagick** [comment]
@numb3r3  I think it should work OOTB, as most Chinese OSS providers also provide some level of S3 compatibility layer.

https://www.alibabacloud.com/help/en/object-storage-service/latest/seamlessly-migrate-data-from-amazon-s3-to-alibaba-cloud-oss#section-ddt-ltg-vdb

**Comment by numb3r3** [comment]
This PR is https://github.com/RaRe-Technologies/smart_open/pull/681 is a good example. This could help us to learn how much effort we need to put in.

**Comment by nomagick** [comment]
I guess we could use the `smart_open` s3 scheme and override the API endpoint.

https://github.com/RaRe-Technologies/smart_open/blob/fe6cf99da8210865037f129968d31690c22f49c6/smart_open/s3.py#L528

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-example-privatelink.html?highlight=endpoint_url#configuring-the-client-endpoint-url

**Comment by numb3r3** [comment]
If it works, that's better. But I'm afraid that the credentials access is broken.

**Comment by ddelange** [comment]
does OSS support multipart uploads via the boto API? if not, you'll have to pass `multipart_upload=False`.

if you instantiate your boto client with the right credentials etc, you can pass your custom client object directly:

```pycon
>>> import botocore, boto3, smart_open, functools
... client = boto3.session.Session().client("s3", config=botocore.client.Config(max_pool_connections=50))
... _open = functools.partial(smart_open.open, transport_params={"client": client})
... with _open("s3://bucket/tmp", "wb") as fp:
...     fp.write(b"...")
3
```

if you need to pass Metadata, ACL etc you can pass them to the multipart upload api:
```py
transport_params={
    "client_kwargs": {"S3.Client.create_multipart_upload": {"Metadata": metadata},
},
```
