### ISSUE TITLE
Investigate capacity to have `async` method for `match` and `find` specially for `Storage Backends`

### ISSUE THREAD

**Issue by JoanFM** [docarray/docarray#446]
Maybe it could be interesting to have an `async` version of `match` and `find` specially for `Storage Backends` which are not CPU-bound.

This would help turn the `Executor` endpoints into `async def`

**Comment by JoanFM** [comment]
Weaviate Async client: https://github.com/semi-technologies/weaviate-python-client/issues/88
ElasticSearch async client: https://elasticsearch-py.readthedocs.io/en/7.x/async.html#getting-started-with-async
Qdrant async client: claim to be https://github.com/qdrant/qdrant_client but not documented
Redis async client: https://redis-py.readthedocs.io/en/stable/examples/asyncio_examples.html

**Comment by hsm207** [comment]
@JoanFM what was the conclusion for weaviate async client?

**Comment by JoanFM** [comment]
Hey @hsm207 we have another ticket tracking the same idea, this is why I closed.

**Comment by hsm207** [comment]
> Hey @hsm207 we have another ticket tracking the same idea, this is why I closed.

which ticket is it? I'd like to subscribe

**Comment by JoanFM** [comment]
#947
