### ISSUE TITLE
DOCS: add docstring for docarray.typing

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#463]
This docs is empty right now : https://docarray.jina.ai/api/docarray.typing/#module-docarray.typing it should not be 

This page is refer to here : https://docarray.jina.ai/fundamentals/dataclass/construct/#construct

**Comment by samsja** [comment]
This docs is empty right now : https://docarray.jina.ai/api/docarray.typing/#module-docarray.typing it should not be

**Comment by JoanFM** [comment]
Will not do as it is
