### ISSUE TITLE
Add `.combine_embeddings()` method do DocumentArray

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#512]
Right now it is painful to combine embeddings from different nesting levels and set them at the top level, especially until [`root_id`](https://github.com/jina-ai/docarray/issues/461) is solved.

So this should do the following: It takes an access path (or list of access paths?) (e.g. @.[image, main_text]), and combines the embeddings in those docs using one of 'sum', 'mean', 'concat', or a provided model.

**Comment by JoanFM** [comment]
Will not do as it is
