### ISSUE TITLE
Consider xarray and/or built-in "array metadata" support?

### ISSUE THREAD

**Issue by NowanIlfideme** [docarray/docarray#52]
Hi, this library is very close to what I've been thinking about for quite a while now: how to standardize data types for ML use. I haven't dug too much into it, besides the docs, but I already love it (especially Pydantic support).

However, one thing that I feel is missing in mainstream ML is a "named tensor" type, which is actually just an ndarray/tensor with semantic metadata. The minimum metadata is **dimensions** of the data, e.g. "feature", "height/width/RGB", "date (time series)", "MCMC draw" and so on. On top of this, **coordinates** let you assign semantic meaning to each index of a dimension (RGB or BRG or HSV? what dates? what latitude/longitude?). [xarray](xarray.pydata.org) is an ndarray that wraps Numpy (or other arrays, including zarr, I believe) with Pandas indices (and more...) and supports this kind of rich metadata.

Since DocArray is "early in life", would you consider having this sort of metadata in the library, or would it be way outside of scope? One way would be to just support _xarray_ as a possible field type, though the serialization would need adjustment. The second way would be to natively support such metadata (which is quite a chore, but would work with Torch/TF/etc tensor types). In the native support version, it seems it could be done by having structured hierarchies of Document with just additional checking... I'll have to play around with that.

FWIW, I briefly thought the name meant "documented array" and got excited (still am, but for a different reason 😋).

**Comment by hanxiao** [comment]
Thanks a lot for your interest!

Supporting `zarr` and `xarray` is definitely in the scope. The biggest challenge here is the wire format & serialization: while a naive implementation should be easily doable, I'm not really sure how to allow zero-copy serialization in `zarr` and `xarray` like in `numpy.ndarray`. I need to dig into their APIs and wire specification.

**Comment by JoanFM** [comment]
Hello @NowanIlfideme ,

We have done a new release (0.30) that rewrites docarray completelly. There we provide TorchTensor object with semantics as you describe here in the ticket. I hope you like it and find it useful.
https://docs.docarray.org/API_reference/typing/tensor/tensor/
