### ISSUE TITLE
Support Aggregation/Faceting on tags

### ISSUE THREAD

**Issue by girishc13** [docarray/docarray#536]
# What is Aggregation or Faceting?
Aggregations/Facets provides a statistics (unique terms, range, counts) along a column or tag data. Statistics such as min and max price range, available color/category/size values provide the user with additional data about the current search result. These are useful and mandatory in the current e-commerce search applications because they enable further filtering of the search results without having to reformulate the search query or guess the available tags. It's a necessary drill down tool to reduce the number of search results in case the number of results are overwhelming. Having aggregation data also allows the front end to be more flexible and tailor the search results display to indicate some properties of the search result such as

- low number of results -> show alternate queries or query reformulations
- high number of queries -> highlight filters with high number of choices for drill down
- divide the search results into multiple grids

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html
https://lucidworks.com/post/faceted-search-with-solr/
https://lucene.apache.org/core/4_0_0/facet/org/apache/lucene/facet/doc-files/userguide.html

**Comment by JoanFM** [comment]
We will reopen this issue later if community specifically needs it
