### ISSUE TITLE
add option to disable list-like behavior (offset2id) and use it in executors

### ISSUE THREAD

**Issue by alaeddine-13** [docarray/docarray#542]
DocArray allows list-like behavior by adding offset2id structure to storage backends. This means the database stores, along with documents, meta information about document order.
This information is only updated/synced when a DA is destroyed or quit the context manager. Furthermore, offset2id is updated in memory in all update operations.
However, offset2id is not useful in indexers where concurrent usage is possible and users do not need information about document location. Besides, updating offset2id is not efficient.
Therefore, it's important to ~~have an option that disables list-like behavior (and offset2id with it)~~ and use it in DocumentArray indexers.
Alternatively, we can have a parent class DocumentStore that encapsulates all DocumentArray functionalities except list-like behavior.

1. identify methods that use offset2id
2. define the DocumentStore class in docarray/array/document.py
3. exclude all methods that use offset2id from DocumentStore
4. DocumentArray class inherits from DocumentStore (optional)
5. Add scan method (optional)

**Comment by dongxiang123** [comment]
Here are all the methods that are using offset2id. 

1. docarray/array/storage/elastic/getsetdel.py
    1. _load_offset2ids
    2. _save_offset2ids
2. docarray/array/storage/base
    1. _del_doc
    2. _del_doc_by_id
    3. _del_doc
    4. insert
3. docarray/array/storage/annlite/backend.py
    1. _load_offset2ids
    2. _save_offset2ids
4. docarray/array/storage/memory
    1. _del_doc_by_id
    2. def _set_doc_by_offset
5. docarray/array/storage/qdrant
    1. _load_offset2ids
    2. _save_offset2ids
    3. _extend
    4. _get_offset2ids_meta
    5. _update_offset2ids_meta
6. docarray/array/storage/redis
    1. _get_offset2ids_meta
    2. _update_offset2ids_meta
    3. _load_offset2ids
    4. _save_offset2ids
    5. _clear_storage
    6. _extend
7. docarray/array/storage/sqlite
    1. _del_doc_by_id
    2. _get_docs_by_offsets
    3. _del_docs_by_ids
    4. _load_offset2ids
    5. _save_offset2ids
    6. _del_docs
    7. _del_doc_by_offset
8. docarray/array/storage/weaviate
    1. _load_offset2ids
    2. _save_offset2ids
    3. _extend
    4. _update_offset2ids_meta
    5. _get_offset2ids_meta
