### ISSUE TITLE
Think about making multimodal as first class citizen in the protobuf

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#547]
# Context

We want docarray to fully support multi modal features. ATM we have the dataclass feature that allow to do this easily. Nevertheless this multiodal feature is not first class citizen. Our protobuf still does not offer the same flexibility as our dataclass. There are two layers, protobuf with chunk and content and dataclass that map the multi modal feature to the protobuf definition.

We should remove the extra layer, make multi modal first class citizen in the protobuf.

This will make the goal of docarray for multi modal clearer  + it will be easier for anybody to ship an interface for docarray in other programming language.

**Comment by JoanFM** [comment]
Please make sure to involve @girishc13 and @dongxiang123 to make sure `docarray` can support every pattern for `vector/traditional` search and `ranking`.

**Comment by samsja** [comment]
the refactoring has been kickoff https://github.com/docarray/docarray/tree/feat-rewrite-v2
