### ISSUE TITLE
Full support of field types in storage backends (for instance redis TAG type not supported)

### ISSUE THREAD

**Issue by alaeddine-13** [docarray/docarray#558]
`TYPE_MAP` attribute in each BackendMix of document stores tries to map standard docarray types into backend specific types with converter. However this means some types are not supported in docarray although possible in backends.
Athough it's not easy to support every type, we can make it generic so that in case a type not supported, we can still attempt to insert it in the database (at the user's own responsibility) as plain text type and the database takes care of casting (no converters at docarray level for these types)

**Comment by JoanFM** [comment]
To be better handled in v2
