### ISSUE TITLE
Add full text search support to qdrant backend

### ISSUE THREAD

**Issue by alaeddine-13** [docarray/docarray#612]
Qdrant added support for full text search in [v0.10.0](https://github.com/qdrant/qdrant/releases/tag/v0.10.0) : https://qdrant.tech/documentation/indexing/#full-text-index
Support this feature in DocArray `find` interface

**Comment by JoanFM** [comment]
Note, this is not real text search, this is text based filtering.

**Comment by JoanFM** [comment]
This is blocked by the update on `qdrant versioning`
