### ISSUE TITLE
Support for tiff images

### ISSUE THREAD

**Issue by radao** [docarray/docarray#654]
Currently `docarray` has the ability to load tiff images but does not support multi-page tiffs, instead returning the first image in the stack. Are there plans to support tiff files?

**Comment by JohannesMessner** [comment]
Hi @radao! How would you these multiple pages to be loaded? To be put into `.chunks`, one page per chunk, or would you expect all pages to be concatenated and stored as one?

**Comment by radao** [comment]
I'm not too familiar with the internals of docarray but for the tiff files I'm working with, there is some global metadata and multiple pages with page specific metadata. I suppose that would mean each page would be better suited as a separate document, or do `.chunks` allow adding metadata?

**Comment by JohannesMessner** [comment]
Chunks are fully fledged Documents, so yes!

Sounds like the best course of action is to put the overall metadata at the root level Document and move the rest into chunks.
I'll ad it to our backlog.
