### ISSUE TITLE
docs: some images are illegible in dark mode

### ISSUE THREAD

**Issue by NicholasDunham** [docarray/docarray#742]
When I view the docs with dark mode turned on, the text in some of those images is impossible to read. The problem is that these images have black text and a transparent background. Here's an example:

![Screenshot 2022-11-09 at 1 45 31 PM](https://user-images.githubusercontent.com/11730795/200961098-40db7bec-4271-4b70-947a-05603861d519.png)

Of course switching to light mode "fixes" the problem, but if we offer dark mode on the docs site we should probably make sure all images work in it.

Here are some images that are affected by this issue:

docs/fundamentals/document/images/nested-structure.svg
docs/fundamentals/documentarray/images/docarray-single.svg
docs/fundamentals/documentarray/images/docarray-array.svg
docs/fundamentals/documentarray/images/docarray-index-example.svg
docs/fundamentals/documentarray/images/docarray-index-example-full2.svg
docs/fundamentals/documentarray/images/docarray-index-example-full3.svg

**Comment by JoanFM** [comment]
Decided not to move with this
