### ISSUE TITLE
docs: copyrighted song lyrics in page

### ISSUE THREAD

**Issue by NicholasDunham** [docarray/docarray#743]
[This page](https://docarray.jina.ai/datatypes/text/#searching-at-chunk-level-with-subindex) has copyrighted song lyrics in it. Although we might not actually get in trouble for this, it's technically copyright infringement unless we're paying to license them.

I can replace the lyrics with public domain text (i.e., anything published before 1927 [US rule] and written by an author who died at least 70 years ago [EU rule]) if you agree it's worth doing.

**Comment by JohannesMessner** [comment]
Done here: https://github.com/docarray/docarray/pull/746
