### ISSUE TITLE
Create a Type abstract class

### ISSUE THREAD

**Issue by dongxiang123** [docarray/docarray#819]
We need to create an common interface via an abstract class for our docarray.typing obj

**Comment by dongxiang123** [comment]
The abstract class should contain the following methods, 1. _to_node_protobuf (Convert Document into a NodeProto protobuf message). 2. from_protobuf (read value from a proto msg) 3. validate (inherited from pydantic about validating data.)

**Comment by samsja** [comment]
done https://github.com/docarray/docarray/pull/824
