### ISSUE TITLE
Weaviate's cosine similarity vs cosine distance

### ISSUE THREAD

**Issue by anna-charlotte** [docarray/docarray#825]
I think, as of right now we mix up cosine similarity and cosine distance in here.
In  `docarray/array/storage/weaviate/find.py` in `FindMixin._find_similar_vectors` cosine_similarity is set as follows:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/73693835/203112089-fa8545ee-a07a-4fb0-ac57-3fed1656e67b.png">

As far as I understood, we need to follow one of the two:
- https://stackoverflow.com/questions/58381092/difference-between-cosine-similarity-and-cosine-distance
- https://weaviate.io/developers/weaviate/current/more-resources/faq.html#q-how-do-i-get-the-cosine-similarity-from-weaviates-certainty

**Comment by JoanFM** [comment]
Make sure what is that they are returning as `distance` and use it properly
