### ISSUE TITLE
Redis failing with disabled list_like behaviour

### ISSUE THREAD

**Issue by anna-charlotte** [docarray/docarray#832]
Redis' [`__len__` method](https://github.com/docarray/docarray/blob/e2d4d19b1f9c3ab0a73d7a7fbe35f4548cf1f7d3/docarray/array/storage/redis/seqlike.py#L30) is based on the `_offset2id` param. If da with `list_like = False` => `len(da) = 0`. 
With this, for example [the match function returns in the very beginning](https://github.com/docarray/docarray/blob/e2d4d19b1f9c3ab0a73d7a7fbe35f4548cf1f7d3/docarray/array/mixins/match.py#L71) due to length of da = 0, without actually matching. 

As far as I understood, this has been implemented this way, because redis does not have an efficient api to get the number of keys, like the other storage backends have.

**Comment by samsja** [comment]
fix in https://github.com/docarray/docarray/pull/840
