### ISSUE TITLE
DocumentArray should inherit from typing.Generic

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#943]
Since DocumentArray can be parametrized with a specific Document class, it has to inherit from `typing.Generic` if we want type checkers to treat it properly.

I suspect that we are currently suppressing a bunch of mypy error due to this, and we should un-suppress them.
Let's make sure that we go through all such cases and try to fix typing properly.

**Comment by JoanFM** [comment]
Please add description to show the reason
