### ISSUE TITLE
Is Chinese retrieval supported in Redis backend

### ISSUE THREAD

**Issue by SuiJiGuoChengSuiJiGuo** [docarray/docarray#952]
RediSearch support chinese retrieval https://redis.io/docs/stack/search/chinese/.  But I can't find a place to configure in 'config' or 'Redis config'.  
I want to ask for help about this feature. 
Thanks.

**Comment by JoanFM** [comment]
Hey @SuiJiGuoChengSuiJiGuo ,

We are working on a PR to expose this possibility

**Comment by SuiJiGuoChengSuiJiGuo** [comment]
Thank you for your help!!!
