### ISSUE TITLE
Can elasticsearch backend support nested data?

### ISSUE THREAD

**Issue by SuiJiGuoChengSuiJiGuo** [docarray/docarray#958]
Elasticsearch supported nested data, while I wonder how can I add a nested data in document array with elasticsearch as backend? And I want to search in `field_1_1`.
 Here is my code: 
`da = DocumentArray(
    storage='elasticsearch', config={'hosts': 'http://localhost:9200', 'index_name': 'test', 'n_dim': 32, }
)`
`da.append(Document(text="hello", tags={"field_1":{"field_1_1":"world1"}, "field_2":{"field_2_1":"world2"}}))`
Can you please help or give some advice? Thanks

**Comment by JoanFM** [comment]
This is supported in new version
